### ISSUE TITLE
Update notification ("Update to Nextcloud ... is available") is not clickable

### ISSUE THREAD

**Issue by caugner** [nextcloud/notifications#1038]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When a Nextcloud update is available, Nextcloud shows a notification to admins. However, this notification is purely informative and is not interactive.

**Describe the solution you'd like**
It would be nice if the Nextcloud update notification would be a link to the "Settings" > "Overview" page (which includes the "Open updater" and "Download now" buttons).

**Describe alternatives you've considered**
(None.)

**Additional context**
![grafik](https://user-images.githubusercontent.com/495429/114154483-bfc08300-9920-11eb-81d2-43097d3b3e06.png)

In this screenshot:
* the "Update to Ransomware protection to version 1.10.0 is available." notification is clickable and gets me to the "Your apps" / "Updates" page.
* the "Update to Nextcloud 20.0.9 is available." notification is not clickable.

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/notifications/pull/883 -.-

Someone forgot to backport 👯

**Comment by caugner** [comment]
Thanks!
