### ISSUE TITLE
automatic color adjustments should take place based on the selected theme color

### ISSUE THREAD

**Issue by j-ed** [nextcloud/notifications#104]
As requested by @juliushaertl (https://github.com/nextcloud/server/issues/7441#issuecomment-350861648) I've created this issue.

## Expected behavior
Depending on the selected theme color the notification alert color, and maybe others, should automatically be adjusted to be still visible.

## Current behavior
No automatic color adjustments seems to take place at all.

### Steps to reproduce
1. Open the admin settings.
2. Change the theming color to `FF0000`.
   ![20171210_nc_theming_color](https://user-images.githubusercontent.com/2572764/33807600-9e0704f6-ddd9-11e7-8e9a-06951ca34fbe.png)

3. Check the notification symbol in the menu bar
![20171210_nc_theming_alert_color](https://user-images.githubusercontent.com/2572764/33807601-a297b830-ddd9-11e7-94d7-b9c0119b5b21.png)

4. The notification alert is nearly invisible.

Better visibility could look like this:
![20171210_nc_theming_alert_better_color](https://user-images.githubusercontent.com/2572764/33807680-b1de6ff4-ddda-11e7-8d7e-5d9dbb83a22c.png)

#### Server Configuration
OS: Linux 3.16.50
Web server: Apache2 2.4.29
Database: MariaDB 10.0.32
PHP version: 5.6.29
Nextcloud version: 12.0.4

#### Client Configuration
Browser: Mozilla Firefox 57.0.2
Operating system: Windows 7

**Comment by nickvergessen** [comment]
Hmm we are not replacing anything on the fly, but I guess we can just add a 3rd version of the bell: white+red, black+red, white+nextcloud-blue

Just need to decide how we determinate that a color is too red.

**Comment by j-ed** [comment]
Although I'm not a developer I stumbled over similar problems years ago where someone has erroneously set e.g. the character color and the background color of an application to the same color 😄 
Wouldn't make sense to implement a kind of automatic check as it is described here:
https://css-tricks.com/reverse-text-color-mix-blend-mode/

**Comment by juliushaertl** [comment]
Do we actually need the red dot there, since we only show the icon if there are notifications available? @nextcloud/designers

**Comment by MorrisJobke** [comment]
> Do we actually need the red dot there, since we only show the icon if there are notifications available? @nextcloud/designers

The plan was to show it permanently: #2

**Comment by nickvergessen** [comment]
We could than still do this with transparency, but I like the additional color, makes it a bit more 🎉

**Comment by MariusBluem** [comment]
> The plan was to show it permanently: #2

PR for showing it permanently is in: https://github.com/nextcloud/notifications/pull/107

**Comment by jancborchardt** [comment]
Ok, so default to the lil red dot, and if the theming color is on the red spectrum, make the dot blue?

Can we do that with theming check and CSS/SVG magic @juliushaertl?

**Comment by juliushaertl** [comment]
Should be fairly simple, if we migrate the notifications app to SCSS.
