### ISSUE TITLE
Dismiss All Notifications

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notifications#105]
Hi, I'm requesting the ability to **Dismiss All Notifications** in bulk rather than individually dismissing each one by clicking on the top right corner.  [Linked from Issue #7403 in the server app; thanks!](https://github.com/nextcloud/server/issues/7403#issuecomment-352814656)
![dismiss-all](https://user-images.githubusercontent.com/1787238/33629196-0fcc0cf6-d9b8-11e7-8ea0-42fe2f2a5a13.png)

**Comment by pixelipo** [comment]
@nextcloud/designers ideas?

**Comment by nickvergessen** [comment]
Maybe we add a button at the end of the list?

Just as a note, this also needs a new endpoint, since such an endpoint does not exist yet.

**Comment by jancborchardt** [comment]
Yeah, a button placed at end of list seems best @nickvergessen :+1:

Should only appear when there are more than 2 notifications though, as it does not make sense for less.

Wording: "Dismiss all notifications" (this capitalization), and left of the text in the button an icon-close to be symmetric with the x-close icons for the individual notifications.
