### ISSUE TITLE
No support for webhooks to push notifications to external apps

### ISSUE THREAD

**Issue by mkrecek234** [nextcloud/notifications#1053]
As not everyone is using the Nextcloud app but has other chat services to inform users of news, it would be great if Notifications offers plugins for external webhooks.

e.g. send notifications to Slack, Telegram, Discourse etc.

Messages should include a weblink to the related item (file/folder/deck board etc.)

Any plans? I'd think this would be standard as it is for most collaboration services

**Comment by tcitworld** [comment]
Maybe this could be done with flow instead ?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/flow_webhooks should do?

**Comment by mkrecek234** [comment]
This app is not on Nextcloud's app store (anymore?), and I can't see how to manually install it nor is there any documentation.

Anyone who can help? 
It would be just nice and easy to route all NC notifications to a webhook.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/flow_webhooks/issues/14
