### ISSUE TITLE
Support webpush for notifications

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/notifications#1054]
All major browsers but Safari support this : https://caniuse.com/push-api

Can replace polling in most cases, and probably even better than using the websocket connection from `notify_push`.

Only the notifications app should subscribe to webpush, so maybe the other apps could benefit from push through the notification app forwarding the information by event-bus ?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notify_push

is already used when installed, since #835 and #837

**Comment by tcitworld** [comment]
Yeah, but this requires notify_push to be setup correctlyand webpush can send notifications even with the tab closed (which can be seen as a feature as well as a nuisance, admittedly). Understood if you don't want the work done twice though.
