### ISSUE TITLE
User bubbles empty

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notifications#1077]
### Steps to reproduce
1. Be mentioned in a talk message, comment or something else that generates a user bubble

### Expected behaviour
Bubble shows

### Actual behaviour
Bubble doesn't show.
Ref https://github.com/nextcloud/nextcloud-vue/issues/2200

Either the problem is fixed before the next release, or we need to downgrade to 4.0.3 again.

**Comment by nickvergessen** [comment]
cc @skjnldsv so you are aware and don't move the issue to the next milestone when the release gets closer

**Comment by blizzz** [comment]
still a thing?

**Comment by skjnldsv** [comment]
Never seen this :shrug:
