### ISSUE TITLE
Push notification sent but response was not parsable, using an outdated push proxy

### ISSUE THREAD

**Issue by xinstein** [nextcloud/notifications#1099]
### Steps to reproduce
1. ./occ notification:test-push --talk {username}

### Expected behaviour
notifications should send and no error should raise

### Actual behaviour
notification is sent but a funny **info** message is recorded:
```
Push notification sent but response was not parsable, using an outdated push proxy? [https://nc.xstereo.top:7443/index.php/apps/ssepush] : {Followed by sth looking like the html of my nextcloud homepage.}
```

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by joshtrichards** [comment]
> `using an outdated push proxy? [https://nc.xstereo.top:7443/index.php/apps/ssepush]`

What is `ssepush`?

**Comment by xinstein** [comment]
it's a third-party push implementation which enables push on googless phones.

> > `using an outdated push proxy? [https://nc.xstereo.top:7443/index.php/apps/ssepush]`
> 
> What is `ssepush`?
