### ISSUE TITLE
Possibility to choose notification of own activity 

### ISSUE THREAD

**Issue by icecko** [nextcloud/notifications#1120]
### Steps to reproduce
After upgrade from 20.0.8 to 21.0.7 self-service notifications do not work. I try upgrade to 22.2.3 but problem is not solved.

### Expected behaviour
I practically created a new directory and added a colleague there, I also put the file there and I waited for half an hour, but so far I have not received any notification, my colleague has.
When we first installed the briefcase, this option could be turned on by any user. Later, that menu option disappeared. 

### Server configuration
Centos7
Aoache
Mariadb10.3
Php 7.3
Nextcloud version: 22.2.3

**List of activated apps:**
Enabled:
  - accessibility: 1.8.0
  - activity: 2.15.0
  - admin_audit: 1.12.0
  - circles: 22.1.1
  - cloud_federation_api: 1.5.0
  - comments: 1.12.0
  - contacts: 4.0.6
  - contactsinteraction: 1.3.0
  - dashboard: 7.2.0
  - dav: 1.19.0
  - federatedfilesharing: 1.12.0
  - federation: 1.12.0
  - files: 1.17.0
  - files_automatedtagging: 1.12.0
  - files_pdfviewer: 2.3.1
  - files_retention: 1.11.1
  - files_rightclick: 1.1.0
  - files_sharing: 1.14.0
  - files_trashbin: 1.12.0
  - files_versions: 1.15.0
  - files_videoplayer: 1.11.0
  - firstrunwizard: 2.11.0
  - impersonate: 1.9.0
  - logreader: 2.7.0
  - lookup_server_connector: 1.10.0
  - nextcloud_announcements: 1.11.0
  - notifications: 2.10.1
  - oauth2: 1.10.0
  - onlyoffice: 7.2.0
  - password_policy: 1.12.0
  - photos: 1.4.0
  - privacy: 1.6.0
  - provisioning_api: 1.12.0
  - recommendations: 1.1.0
  - serverinfo: 1.12.0
  - settings: 1.4.0
  - sharebymail: 1.12.0
  - support: 1.5.0
  - survey_client: 1.10.0
  - systemtags: 1.12.0
  - text: 3.3.0
  - theming: 1.13.0
  - twofactor_backupcodes: 1.11.0
  - updatenotification: 1.12.0
  - user_status: 1.2.0
  - viewer: 1.6.0
  - weather_status: 1.2.0
  - workflowengine: 2.4.0
Disabled:
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": false,
        "trusted_domains": [
            "localhost",
            "aktovka.udzs-sk.sk"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "22.2.3.0",
        "overwrite.cli.url": "https:\/\/aktovka.udzs-sk.sk\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "nc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "default_phone_region": "SK",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0",
            "timeout": "1.5"
        },
        "filelocking.enabled": "true",
        "enable_previews": "true",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "preview_max_x": "1024",
        "preview_max_y": "768",
        "preview_max_scale_factor": "1",
        "log_type": "file",
        "logfile": "\/mnt\/ncdata\/nextcloud.log",
        "loglevel": "1",
        "logfilemode": 416,
        "logdateformat": "F d, Y H:i:s",
        "log_rotate_size": 1073741824,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_sendmailmode": "smtp",
        "force_language": "sk",
        "maintenance": false,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "activity": {
            "enable_email": "yes",
            "enabled": "yes",
            "installed_version": "2.15.0",
            "notify_email_calendar": "0",
            "notify_email_calendar_event": "0",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "1",
            "notify_email_favorite": "1",
            "notify_email_file_changed": "1",
            "notify_email_file_created": "1",
            "notify_email_file_deleted": "1",
            "notify_email_file_favorite_changed": "0",
            "notify_email_file_restored": "1",
            "notify_email_public_links": "0",
            "notify_email_remote_share": "0",
            "notify_email_shared": "1",
            "notify_email_systemtags": "0",
            "notify_notification_calendar": "0",
            "notify_notification_calendar_event": "0",
            "notify_notification_calendar_todo": "0",
            "notify_notification_comments": "0",
            "notify_notification_favorite": "0",
            "notify_notification_file_changed": "0",
            "notify_notification_file_favorite_changed": "1",
            "notify_notification_group_settings": "1",
            "notify_notification_personal_settings": "0",
            "notify_notification_public_links": "0",
            "notify_notification_remote_share": "0",
            "notify_notification_security": "1",
            "notify_notification_shared": "0",
            "notify_notification_systemtags": "0",
            "notify_setting_batchtime": "0",
            "notify_setting_self": "0",
            "notify_setting_selfemail": "0",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "11724"
        },
        "circles": {
            "enabled": "yes",
            "installed_version": "22.1.1",
            "loopback_tmp_path": "\/",
            "loopback_tmp_scheme": "https",
            "maintenance_run": "0",
            "maintenance_update": "{\"maximum\":3,\"3\":1637844302,\"2\":1637847001,\"1\":1637847001,\"4\":1637805609,\"5\":1637809201}",
            "types": "filesystem,dav"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "4.0.6",
            "types": "dav"
        },
        "contactsinteraction": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "dav"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1597860280.7642",
            "lastcron": "1637847002",
            "lastupdateResult": "[]",
            "lastupdatedat": "1637815502",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_default_permission_candelete": "no",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permissions": "5",
            "theming.variables": "a7c9aa6acd1661349947e0e4b33100d3",
            "updater.secret.created": "1637778112",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "7.2.0",
            "types": ""
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.19.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "1000",
            "default_quota": "3 GB",
            "enabled": "yes",
            "installed_version": "1.17.0",
            "types": "filesystem"
        },
        "files_automatedtagging": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": ""
        },
        "files_retention": {
            "enabled": "yes",
            "installed_version": "1.11.1",
            "notify_before": "no",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.15.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "logging"
        },
        "impersonate": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "levels": "11111",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerUrl": "https:\/\/oo.aktovka.udzs-sk.sk\/",
            "enabled": "yes",
            "installed_version": "7.2.0",
            "sameTab": "true",
            "types": "prevent_group_restriction"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "authentication"
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "serverinfo": {
            "cached_count_filecache": "134774",
            "cached_count_storages": "549",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "support": {
            "SwitchUpdaterServerHasRun": "yes",
            "enabled": "yes",
            "installed_version": "1.5.0",
            "last_notification": "1637847002",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "3.3.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "backgroundColor",
            "cachebuster": "15",
            "color": "#FFFFFF",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.13.0",
            "logoMime": "image\/jpeg",
            "name": "\u00darad pre doh\u013ead nad zdravotnou starostlivos\u0165ou",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": ""
        },
        "updatenotification": {
            "contacts": "4.0.6",
            "core": "22.2.3.0",
            "enabled": "yes",
            "files_automatedtagging": "1.9.1",
            "files_retention": "1.9.1",
            "installed_version": "1.12.0",
            "onlyoffice": "7.2.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "weather_status": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.4.0",
            "types": "filesystem"
        }
    }

### Client configuration
Chrome, Mozilla
Windows10

**Comment by nickvergessen** [comment]
It is expected to not receive notifications for own actions
