### ISSUE TITLE
no notifications for as favorites tagged directories 

### ISSUE THREAD

**Issue by eaCodet** [nextcloud/notifications#1130]
I am getting no notifications for directories that I tagged as favorites. For all other directories notifications work, but not if I only activate notification service for my favorite directories.
Strangely, the notification service for favorite directories does work for the activity "sharing by email" and if a shared-by-email-file is downloaded.

Is a server setting missing or is this really a nextcloud issue? 

Hope someone can help!

**Comment by nickvergessen** [comment]
You are not running the latest version, correct?

**Comment by eaCodet** [comment]
The server is running with Nextcloud 20.0.12

**Comment by nickvergessen** [comment]
20 is not supported anymore. please update

**Comment by eaCodet** [comment]
thank you!

**Comment by eaCodet** [comment]
The server is now running with nextcloud 22.2.3. Still the same problem: notifications do generally work, but not as intended just for the objekts tagged as favorites. 
Hope someone can help.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/31081

It's a misunderstanding
