### ISSUE TITLE
Sound on talk notifications

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notifications#116]
https://github.com/nextcloud/spreed/issues/627

**Comment by kebekus** [comment]
Thank you for the quick reaction. This feature would make such a big difference for me…

**Comment by nickvergessen** [comment]
Hmm sound is currently not supported in any browser:
https://developer.mozilla.org/en-US/docs/Web/API/Notification/sound

So we can only play sound manually.

**Comment by MorrisJobke** [comment]
@nickvergessen Will this be ready by later today or should we move it to 13.0.2? nextcloud/server#8748

**Comment by nickvergessen** [comment]
No response for the license so far, so I guess no.

**Comment by nickvergessen** [comment]
Closing as per https://github.com/nextcloud/notifications/pull/117#issuecomment-404854353

**Comment by nickvergessen** [comment]
So I checked this a bit more and it still is like this:
* Firefox: allows autoplaying in "onclick" handlers as well as after "enough" interactions, whatever that means, can but doesn't have to be reliable
* Chrome/Chromium: same as above https://developers.google.com/web/updates/2017/09/autoplay-policy-changes
* Safari: still not allowing autoplaying without interaction, even after manually adding it manually to the list: https://support.shadowhealth.com/hc/en-us/articles/360009548313-Audio-issues-in-Safari

**Comment by kebekus** [comment]
Dear nickvergessen,

thank you for coming back to this! I am a little confused at this point because the web-site "spreed.me" as well as the web-version of the "Element" Matrix client manage to send out ring tones from the browser reliably. I do not know, however, how they do that.

Best,

Stefan.

**Comment by nickvergessen** [comment]
Interesting, so I dove a bit into the unminified code of the Spreed.Me and it seems to use: https://github.com/goldfire/howler.js
Something to look into in the next time window

**Comment by nickvergessen** [comment]
Created a draft at https://github.com/nextcloud/notifications/pull/1169 and it seems to be working in general.
