### ISSUE TITLE
Distribute external information to all users or user groups

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/notifications#1207]
### Steps to reproduce
1. use a hosted nextcloud service (like Hetzner)
2. Hetzner announces maintenance - to the mail accounts stored in their customer database.
3. the client admin has to distribute the maintenance announcement  to all nextcloud users.

### Expected behaviour
the possibility to inject or pick up external messages to notifications  - from a dedicated email account or a dedicated nextcloud talk user "nc-server"

### Actual behaviour
manual intervention necessary.

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Where did you install Nextcloud from:**

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/blob/master/docs/admin-notifications.md aims to exactly allow stuff like this.
Currently groups/all is missing but that's in #121
