### ISSUE TITLE
EMail Notification change & conflicting HTML ID attribute?

### ISSUE THREAD

**Issue by EngelPika32** [nextcloud/notifications#1259]
Related issue (with images) for activity-app: https://github.com/nextcloud/activity/issues/897  

 

### Steps to reproduce

Updated from NC22 *(latest patch)* to NC23 *(latest patch)*.

Since that update an additional option appeared under `settings/user/notifications`. [The top one from the images.]

### Expected behaviour
No un-asked e-mail notification. 
I dunno what these "unhandled notifications" are, but I never asked to receive E-Mails for stuff I've selected "push" for. 

Additionally, I don't see any admin option about this to set defaults.

### Actual behaviour
Un-asked e-mail notification from (apparently) a new option.    
The HTML code includes ID conflicts (more than one element with the same ID).
- - - - -

PR adding the new option: https://github.com/nextcloud/notifications/pull/1074
File (in notifications): `src/views/UserSettings.vue:30`
File (in activity): `templates/settings/form.php:73`

One of these has to change their ID.

- - - - -
### Server configuration

**Operating system**: Arch Linux

**Web server:** caddy

**Database:** MariaDB

**PHP version:** 8.0

**Nextcloud version:** (see Nextcloud admin page) 23.0.8

**Where did you install Nextcloud from:** Docker (fpm)

**Signing status:** `No errors have been found.`

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by nickvergessen** [comment]
Great find. Let's adjust it in this app, as the activity app got some rework and migration to another JS code base in the meantime, so backporting there is much harder
