### ISSUE TITLE
invalid session question

### ISSUE THREAD

**Issue by CezaryGoralski** [nextcloud/notifications#126]
Hello, I would like to ask for help.
Currently I’m writing my own Android application and I want to integrate it with nextcloud notifications. I’m using  request: `POST /ocs/v2.php/apps/notifications/api/v2/push with` :

1. Heders:
- OCS-APIRequest: true
- Authorization: basic (myusername:myuserpassword).base64

2.	Params:
- format: json
- pushTokenHash: tokenhash
- devicePublicKey: firebasetoken
- proxyServer: https://myurl
And I’m receiving response:
`{  
   "ocs":{  
      "meta":{  
         "status":"failure",
         "statuscode":400,
         "message":null
      },
      "data":{  
         "message":"INVALID_SESSION_TOKEN"
      }
   }
}`
In order this to work I have to create session with nextcloud login flow, like in for example nextcloud-talk? Or there is some other way?
Thank you in advance for help.

**Comment by nickvergessen** [comment]
It does not work with the password, you need to use an app password/app token (you can generate them on the personal page).
If you want to login with the password on your app and request an app password directly, there is an endpoint which allows you to do this. Maybe @tobiasKaminsky can assist you.

**Comment by CezaryGoralski** [comment]
Ok thank you very much for fast response. First, I will try to find endpoint app password generation by myself if I doesn’t succeed I will ask him.
