### ISSUE TITLE
Arrow missing from popover

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/notifications#1267]
Was there already before the new ui pr was merged, but should probably be fixed:

![Screenshot 2022-09-01 at 17 48 53](https://user-images.githubusercontent.com/3404133/187957635-b7117f0d-45f1-40e1-967d-3332170f9f8e.png)

**Comment by nickvergessen** [comment]
Works fine locally. But we will see and retest when updating the vue lib in this repo

**Comment by nickvergessen** [comment]
Still works fine here.
