### ISSUE TITLE
Sound on federated share request

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notifications#127]
I’d like there to be a sound for incoming *remote* federated share requests that arrive as a notification, awaiting my approval.  #116 is similar, but for a different app.

Edit: it might also make sense to play a sound for the sender of the remote share if it is approved/rejected

**Comment by nickvergessen** [comment]
@jancborchardt what do you think?
I think playing a sound for all notifications is just too much?!

**Comment by Gaeldrin** [comment]
@nick Honestly, I would love sound on all notifications. I guess it boils down to each user case but the notifications are almost invisible for me the way they are now (the tiny red dot if I'm not missing something). I would love sound to be played and/or pop-up window, preferably in contrast colour too. Best of all, make it configurable so each user can choose.

**Comment by sunjam** [comment]
@Gaeldrin hi, that sounds like a different issue request

**Comment by Gaeldrin** [comment]
@sunjam Guilty as charged, my apologies if it bothers you. I simply didn't believe someone has not asked for sound on notifications so I searched for sound-related issues first, found a few including yours, and replied to @nickvergessen's question. If it's any problem, feel free to suggest a course of action to fix it, I'll comply.

**Comment by sunjam** [comment]
@Gaeldrin pardon my brevity.  I just recommend starting a new issue and referencing this issue #.

On my request... I'm specifically speaking about incoming federated shares.  Notifications are an uncommon thing for me to receive and usually the sender is letting me know to keep an eye out for for their timely, incoming federated share...

- I keep an eye on my desktop app for those little activity notifications that pop up... nothing.
- I log into the webui, looking for some browser popup or _sound cue_.  Nothing
- I check Activity App... nothing
- I check in with the sender via some external source (email, telegram, phone, etc.) on whether the share was sent.
- On a much closer inspection or browser refresh, I notice the small red emblem on Notifications, which once selected asks if I would like to accept the share.
- If I accept or reject the share, I'm not sure of whether the the sender is notified, so I'll just let them know personally.

For me this process could be much more direct and in my face/ears.  If someone sends me a federated share, I would want to confirm as quickly as possible.

**Comment by jancborchardt** [comment]
@nickvergessen I’d say to best integrate with the browser-based web notifications API: https://developer.mozilla.org/en-US/docs/Web/API/notification – that handles notifications from websites properly in a central place.

**Comment by nickvergessen** [comment]
We already do that. The question is whether we want to have s Sound or not

**Comment by jancborchardt** [comment]
@nickvergessen ah right. So sounds for notifications which need to be acted upon make sense. And an incoming federated share is that.

**Comment by nickvergessen** [comment]
Sadly enough this only works in Firefox, all other browsers prevent playing sounds that where not started by the user directly. So you would need to press a "play" button everytime you open a new page.

That is too much of a hassle, so we are not going to do that:
https://github.com/nextcloud/notifications/pull/117#issuecomment-404854353
