### ISSUE TITLE
[Feature request] Notification to be added for the ‘share a folder by e-mail’ feature (according to GDPR rules)  [€500] 

### ISSUE THREAD

**Issue by amzen** [nextcloud/notifications#128]
We want a new feature that can be a good one for the community.
It seems simple. We have a **budget of €500 ** for it.
Thank you to contact me directly if you can do it robust and well built. Tell me the Nextcloud app you have already done.

### Expected behaviour and Actual behaviour
It concerns the feature that allow to share a folder with an email address.
Presently when a file is added or modified in a folder, the activity management allows to register it and to sent email notifications only to registered users, thanks to activity settings.
This new app would be an extension of the activity app as to notify the email addresses designated in a shared folder only when a file is added or updated somewhere in the subtree of the folder.
To fit with GDPR rules, I give below some precaution for messages.

###  Design
As completely managed by recipient, the only visible thing in Nextcloud will be:

SETTINGS
The frequency to send notification emails to shared emails will be set by an admin
in SETTINGS > Activity, at the bottom of the page, to be added :

Default settings (existing Title)

Configure the default activity notification for new user.(existing sentence)

 . . . .  (existing)

Configure the default activity notification for e-mails. (new sentence)

Send emails : Daily, Weekly     and NOT Hourly   to avoid spam feeling
                       (drop down with same design as the other Send emails)

MULTI LINGUAL : Yes
Thank you to use the l10n language system to manage foreign languages.

EMAIL MESSAGES with opt-in opt-out rules

FIRST MESSAGE
Would be the same message sent to new shared email with an add :
To fit with new opt-in rules, thank you to add a new sentence and an action button at the bottom of the welcome mail message :

"I opt-in to receive email notifications of this folder’s update [ I opt-in ] (button)
 I will have the choice to opt-out each time I receive a notification."

The default setting for each ‘share a folder e-mail’ is opt-out
If the recipient click the opt-in button, the setting for this user will be
turned to yes for "A new file or folder has been created"
and turned to yes for "A file or folder has been changed or renamed"

NOTIFICATION MESSAGES
For the notification message dedicated to shared by email, the same design as the classic notification message is used.
At the bottom of this message dedicated to shared emails, an opt out text is added :

"I don’t want to receive any more notifications from this folder [ I opt-out ] (button)"
If the button is clicked by recipient, it disable the notification feature for this e-mail in this folder.

**Comment by nickvergessen** [comment]
That sounds like a very nice idea, let me think a bit about it.

**Comment by amzen** [comment]
Hello Joas,
Very glad to see this idea is welcome. How do you see the development of this feature? Are you personally interested to do it or do you think about someone to make it ? 
I would be glad to talk about it, either here or private with NC Forum [https://help.nextcloud.com/t/a-post-in-activity-notification-to-be-added-for-the-share-a-folder-by-e-mail-feature-according-to-gdpr-rules-budget-requires-staff-attention/31104]
Kind regards,  Hugues

**Comment by nickvergessen** [comment]
Im closing this, since it's not a feature request to the notifications app.

If it should be integrated in an existing app, it would be the activity app, but I'm not sure if we should do that, or if it should just be a new app instead.
