### ISSUE TITLE
[25.0.0RC4] JS errors related to push proxy

### ISSUE THREAD

**Issue by PVince81** [nextcloud/notifications#1326]
<img width="457" alt="image" src="https://user-images.githubusercontent.com/277525/195873001-596394da-6750-451e-8907-cc6d2b661a7b.png">

observed on c.nc.com

**Comment by PVince81** [comment]
@nickvergessen not sure if env issue or bug ?

**Comment by PVince81** [comment]
https://github.com/nextcloud/notifications/blob/v25.0.0rc4/src/NotificationsApp.vue#L225

**Comment by nickvergessen** [comment]
Doing exactly like the readme says:
https://www.npmjs.com/package/@nextcloud/notify_push

I have no clue which repo this is coming from. NPM does not tell and I couldn't find anything in our org.
Is it https://github.com/icewind1991/notify_push-client ?

The again, neither part changed in a long time.

@icewind1991 aware of anything?

**Comment by icewind1991** [comment]
might be https://github.com/icewind1991/notify_push-client/pull/5, will push a release with it included

**Comment by icewind1991** [comment]
pushed a release

**Comment by nickvergessen** [comment]
Confirmed with the new version the error is gone and notifications are instant again:
https://github.com/nextcloud/notifications/pull/1345
