### ISSUE TITLE
Browser notification not blocked while in DnD mode

### ISSUE THREAD

**Issue by PVince81** [nextcloud/notifications#1375]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
1. Setup Nextcloud 25.0.1 with the matching Talk version
2. Open Talk
3. Allow the browser to send notifications
4. Set status to "Do not disturb"
5. Have someone ping you privately or in a group chat

### Expected behaviour
No browser notification sent.

### Actual behaviour
Browser notification still arriving.

## Talk app

**Talk app version:** the one from c.nc.com

## Browser

**Operating system:** openSUSE Tumbleweed

**Browser name:** Firefox

**Browser version:** 107.0

### Browser log

<details>
```
Insert your browser log here, this could for example include:
a) The javascript console log
b) The network log
c) ...
```

</details>

## Server configuration

**Nextcloud Version:** 25.0.1 (c.nc.com)

**List of activated apps:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your server installation folder
```
</details>

**Nextcloud configuration:**

<details>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
</details>

### Server log (data/nextcloud.log)
<details>

```
Insert your server log here
```
</details>

**Comment by PVince81** [comment]
@nickvergessen I don't remember, it felt like I had set it earlier but can't confirm

it did look like I received the notification within a minute or two of Andy posting

**Comment by PVince81** [comment]
@nickvergessen I just got pinged in private and didn't receive a notification, so your theory about the 15 minutes might be correct

still, it would be good to find a way to block this. usually the first minutes of setting to DnD is when I feel the most frustrated (and other users possibly too), so receiving more notifications there is more annoying :smile: 

not sure if blocking also on desktop client level makes sense also

**Comment by nickvergessen** [comment]
> not sure if blocking also on desktop client level makes sense also

Yeah, if DND is set the desktop should not show notifications. They might interfer with screenshares etc.

**Comment by nickvergessen** [comment]
Should be possible to subscribe to the event: `user_status:status.updated`

https://github.com/nextcloud/spreed/blob/2c55fda8fe59a1e3c57b08d44bdf30b393581794/src/components/RightSidebar/Participants/CurrentParticipants/CurrentParticipants.vue#L103-L109

Will check that. Thanks for the confirmation
