### ISSUE TITLE
执行 sudo -u nginx php /usr/share/nginx/nextcloud/cron.php 出现错误

### ISSUE THREAD

**Issue by ZackHou** [nextcloud/notifications#1380]
我在执行sudo -u nginx php /usr/share/nginx/nextcloud/cron.php 日志中会出现报错，我不清楚问题出现哪，nextcloud版本：25.0.1 PHP 8.0.13 OS：Rocky Linux release 9.0 ，nginx version: nginx/1.22.0 日志如下
{"reqId":"5hgZGQbrt2OSEVv7AbU6","level":3,"time":"2022-11-25T18:25:04+00:00","remoteAddr":"","user":"--","app":"notifications","method":"","url":"--","message":"Expected response code 354 but got code \"503\", with message \"503 Error: need RCPT command\r\n\"","userAgent":"--","version":"25.0.1.1","exception":{"Exception":"Swift_TransportException","Message":"Expected response code 354 but got code \"503\", with message \"503 Error: need RCPT command\r\n\"","Code":503,"Trace":[{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":344,"function":"assertResponseCode","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php","line":305,"function":"executeCommand","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":392,"function":"executeCommand","class":"Swift_Transport_EsmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":499,"function":"doDataCommand","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":518,"function":"doMailTransaction","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","line":206,"function":"sendTo","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php","line":71,"function":"send","class":"Swift_Transport_AbstractSmtpTransport","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/private/Mail/Mailer.php","line":191,"function":"send","class":"Swift_Mailer","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/notifications/lib/MailNotifications.php","line":217,"function":"send","class":"OC\\Mail\\Mailer","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/notifications/lib/MailNotifications.php","line":168,"function":"sendEmailToUser","class":"OCA\\Notifications\\MailNotifications","type":"->"},{"file":"/usr/share/nginx/nextcloud/apps/notifications/lib/BackgroundJob/SendNotificationMails.php","line":49,"function":"sendEmails","class":"OCA\\Notifications\\MailNotifications","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/Job.php","line":78,"function":"run","class":"OCA\\Notifications\\BackgroundJob\\SendNotificationMails","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":103,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/usr/share/nginx/nextcloud/lib/public/BackgroundJob/TimedJob.php","line":93,"function":"start","class":"OCP\\BackgroundJob\\TimedJob","type":"->"},{"file":"/usr/share/nginx/nextcloud/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\TimedJob","type":"->"}],"File":"/usr/share/nginx/nextcloud/3rdparty/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php","Line":459,"message":"Expected response code 354 but got code \"503\", with message \"503 Error: need RCPT command\r\n\"","exception":{},"CustomMessage":"Expected response code 354 but got code \"503\", with message \"503 Error: need RCPT command\r\n\""}}

**Comment by nickvergessen** [comment]
Please make sure you configured your mail server correctly.
Once the test mail worked please report your issue in English, so we can help you.
