### ISSUE TITLE
Question / Suggestion

### ISSUE THREAD

**Issue by rotdrop** [nextcloud/notifications#1391]
Is it already possible for other front-end javascript code to get notified by the notifications app? In my case created PDFs and extract archives from an action in the files-view. This can be done in the background and the user gets notified when things are ready or have failed. It would sometimes be nice to refresh the file-listing after successful completion. For this it would be nice if the notifications javascript code could trigger an event that other code could listen on.

**Comment by nickvergessen** [comment]
There is already an old style jquery event which does exactly this (check server repo for the listening part)

* In #728 an attempt is made to move to the proper future syntax

**Comment by rotdrop** [comment]
Thanks! I'll have a look. Sorry for not coming back earlier to this issue ...
