### ISSUE TITLE
[BITV] Dismiss button is highlighted by default

### ISSUE THREAD

**Issue by SystemKeeper** [nextcloud/notifications#1440]
### Steps to reproduce
1. Receive a notification and open it

### Expected behaviour
<img width="365" alt="image" src="https://user-images.githubusercontent.com/1580193/215470178-a0873cd1-1305-4aac-8cf9-e7804b8fe950.png">

### Actual behaviour
<img width="367" alt="Bildschirm­foto 2023-01-30 um 12 52 07" src="https://user-images.githubusercontent.com/1580193/215470108-ad4ac28f-bd2d-4ade-94fc-07c816cffceb.png">

The screenshots above are from safari, but happens on chrome too (just having the button rounded):
<img width="358" alt="image" src="https://user-images.githubusercontent.com/1580193/215470585-37c85e74-ab39-4dd8-87a0-c5069ab1ca65.png">

### Server configuration

Tested with 
```
sudo docker run -it \                                 
    -e SERVER_BRANCH=master \
    -e TALK_BRANCH=master \
    -e NOTIFICATIONS_BRANCH=master \
    -e TRUSTED_DOMAIN=192.168.178.108 \
    --name nextcloud-easy-test-master \
    -p 443:443 \
    ghcr.io/szaimen/nextcloud-easy-test:latest
```

Master was at 1779f4f2e2d9b97f2b286f20cc5e9d8ae8547899.

The same happens with 25.0.3. So not sure if this is a bug or intended to highlight the first close button.

**Comment by nickvergessen** [comment]
This is done by HeaderMenu.vue
It focuses the first targetable thing for accessibility reasons.

Not sure what would be a better approach, as there could be an activity without interactive element nor actions as well.
cc @Pytal

**Comment by Pytal** [comment]
We could make the focus border only appear when keyboard focused by setting the style on `:focus-visible` instead of `:focus`

Would it pass the accessibility audit if we only show the focus border when opening the menu with keyboard but not mouse @michaelnissenbaum?

**Comment by Pytal** [comment]
> We could make the focus border only appear when keyboard focused by setting the style on `:focus-visible` instead of `:focus`
> 
> Would it pass the accessibility audit if we only show the focus border when opening the menu with keyboard but not mouse @michaelnissenbaum?

Confirmed to be accessible by @michaelnissenbaum
