### ISSUE TITLE
Push Notifications to Android phones not working for Nextcloud Talk chats

### ISSUE THREAD

**Issue by matzzzl** [nextcloud/notifications#1466]
Since today I have the problem that Push Notifications to Android phones do not seem to work when using the Nextcloud talk chat.

I tried to debug the problem with tcpdump and Wireshark:

- The domain push-notifications.nextcloud.com is successfully resolved by a DNS-Query
- Nextcloud establishes a TCP-Connection to 95.217.53.153 (c0005.customerpush.nextcloud.com) and exchanges TLSv1.3 encrypted packages with that server

Unfortunately the push notifications to not seem to reach the android phones (tried with 2 different ones), although 2 days ago everything seemed to work.

**Comment by nickvergessen** [comment]
There was a network error:
```
Post "https://fcm.googleapis.com/fcm/send": dial tcp: lookup fcm.googleapis.com: Temporary failure in name resolution
```

We reconfigured a DNS server and it seems to work again.

Thanks for notifying

**Comment by matzzzl** [comment]
My tests confirm that it works again.

Thanks for solving this problem :slightly_smiling_face:
