### ISSUE TITLE
 Can’t able to view the image(Icon avatar) in Email Notification from nextcloud 

### ISSUE THREAD

**Issue by dinesh-dot-com** [nextcloud/notifications#1503]
Hello, I am experiencing a 403 error when trying to view the avatar in my Email notification. Despite trying various techniques, I have been unable to resolve this issue. Would anyone be able to assist me in resolving this problem? Thank you.

![Screenshot (514)](https://user-images.githubusercontent.com/105905278/230596620-2b6b5fe4-d46b-48b7-a2e3-9a37a7221d55.jpg)

**Comment by nickvergessen** [comment]
I guess google asked at some point if you want to see images from remote hosts and you said "no".
Since also the logo is blocked, this is not an issue of the notifications app code and I'm closing it.
