### ISSUE TITLE
Support Web Push Notifications by Apple

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/notifications#1537]
Dear Nextcloudians,

with iOS 16.4 Apple finally implemented Web Push Notifications (years and years after Android, regarding to mobile......)

**Do you already support it, or is it on the roadmap?** It would be just awesome and it would instantly enhance many of the Plugins that exist for Nextcloud

Looks like it needs to be implemented either on each Server, or at a Server on your Side, please see:
- High Level Info: 
  - Apple Developer [VIDEO](https://developer.apple.com/videos/play/wwdc2022/10098/) that introduced the Feature for macOS Safari last year
  - https://webkit.org/blog/12945/meet-web-push/
- Lower Level Info: 
  - Apple [Sending web push notifications in web apps, Safari, and other browsers](https://developer.apple.com/documentation/usernotifications/sending_web_push_notifications_in_web_apps_safari_and_other_browsers)
    - [Sending VAPID](https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/) identified WebPush Notifications via Mozilla’s Push Service
  -  Great Overview Articles: https://web.dev/push-notifications-web-push-protocol 
      - General: https://web.dev/sending-messages-with-web-push-libraries/
      - Send https://web.dev/sending-messages-with-web-push-libraries/ + Receive https://web.dev/push-notifications-handling-messages/ + ...

![image](https://web-dev.imgix.net/image/C47gYyWYVMMhDmtYSLOWazuyePF2/jjHOGQvZttcOEij3c6UR.svg)

(i think the part of requesting Permissions links to here: [NotificationsApp.vue](https://github.com/nextcloud/notifications/blob/master/src/NotificationsApp.vue)
`			window.Notification.requestPermission()
...` but where is the service worker, that could consume the received notification..)

best regards,
ghk

**Comment by nickvergessen** [comment]
This is not on our roadmap in the foreseeable future. We have desktop client and mobile apps already which you can use to get notifications.

**Comment by githubkoma** [comment]
@nickvergessen Oh ok, i understand.. i would love that feature for a plugin to notify users that dont use talk or the files app

Could you or someone point me to the correct files that should be involved? that would be great
- Client
  - [NotificationsApp.vue](https://github.com/nextcloud/notifications/blob/master/src/NotificationsApp.vue) ?
  - Where is the Serviceworker that could consume the Notification?
  - ...
- Server
  - notification route to receive the subscription
  - Service/Controller that already communicates to Pushservers
  - ...

i am thankful for any hint,
thanks in advance,
ghk

**Comment by nickvergessen** [comment]
> [NotificationsApp.vue](https://github.com/nextcloud/notifications/blob/master/src/NotificationsApp.vue) ?

I guess so

> Where is the Serviceworker that could consume the Notification?

We don't have a Service worker

> notification route to receive the subscription

What subscription?

> Service/Controller that already communicates to Pushservers

https://github.com/nextcloud/notifications/blob/master/lib/Push.php

**Comment by githubkoma** [comment]
>> Service/Controller that already communicates to Pushservers

> https://github.com/nextcloud/notifications/blob/master/lib/Push.php

thank you!

>>Where is the Serviceworker that could consume the Notification?

>We don't have a Service worker

Oh, i thought so, because you can install Nextcloud as a PWA, i thought in that case a ServiceWorker is needed to be registered in some Manifest File

>>notification route to receive the subscription

>What subscription?

The Client "subscribes" to the WebPush Notification Service as mentioned here: https://web.dev/push-notifications-subscribing-a-user/#what-is-a-pushsubscription

**Comment by nickvergessen** [comment]
> Oh, i thought so, because you can install Nextcloud as a PWA, i thought in that case a ServiceWorker is needed to be registered in some Manifest File

Not sure what PWA is, but no the notifications app is not providing a manifest or anything anywhere.

> The Client "subscribes" to the WebPush Notification Service as mentioned here: https://web.dev/push-notifications-subscribing-a-user/#what-is-a-pushsubscription

Yeah, but as said we don't need or want this ourselves at the moment. We have various client available and otherwise you need to have a tab of Nextcloud open in your browser to receive notifications.

**Comment by githubkoma** [comment]
> We have various client available and otherwise you need to have a tab of Nextcloud open in your browser to receive notifications.

This is the advantage of [mozillas standardized web push notification](https://developer.mozilla.org/en-US/docs/Web/API/Push_API) approach, and in mozillas/apples case: You don't have to have any browser open, the push notification is triggered by their push notification servers directly to the mobile devices operating system

> Yeah, but as said we don't need or want this ourselves at the moment. 

Yes, thanks so far, the information you gave me already helped and perhaps someone builds this into a separate plugin or so in the future

thanks and best regards,
ghk

**Comment by githubkoma** [comment]
The approach over at https://github.com/nextcloud/notifications/issues/1225 looks really sophisticated
