### ISSUE TITLE
App icon not visible on white theming

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#155]
![screenshot from 2018-08-14 13-20-53](https://user-images.githubusercontent.com/925062/44088912-22c43a62-9fc5-11e8-9f96-7c94a6680e83.png)

Does this need another icon, or something in the code? cc @juliushaertl @nextcloud/theming @nickvergessen

**Comment by juliushaertl** [comment]
@jancborchardt Does it work when you reload the page after changing the theming color to white?

**Comment by juliushaertl** [comment]
We had an extra rule inside of the theming app to overwrite the icon for preview, but I think the general styling was handled in the notifications app. Since that one has moved from a background image to a `<img>` element, the preview is probably broken.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/blob/master/src/App.vue#L62

Does this not work anymore?

**Comment by juliushaertl** [comment]
Just tested, it works fine after reloading. Only the live preview after changing the theming color doesn't work anymore.

**Comment by nickvergessen** [comment]
Right, because vue.js doesn't recalculate the value
