### ISSUE TITLE
customize the body of the email

### ISSUE THREAD

**Issue by romapao** [nextcloud/notifications#1601]
Hello, I use Nextcloud as a container for the documents produced by my office for all my clients who are Nextcloud users. I use notifications to send an email to each client/user as soon as I upload a document to their shared folder. It would be helpful to be able to customize the body text of the email sent by the notification system. Is it already possible? If not, is it possible to implement a console to modify and customize the text of the email sent with the notification system? Thank you.

**Comment by nickvergessen** [comment]
you mean the email as a whole? Or which part?
Can you share a screenshot of the section you mean?

**Comment by romapao** [comment]
I would like to be able to customize the email that is sent by the notification system when a file is uploaded to the user's folder
<img width="1366" alt="Screenshot 2023-07-07 alle 16 42 48" src="https://github.com/nextcloud/notifications/assets/138813270/c4479f48-1c6f-4886-8b38-742d9f16a4f2">

**Comment by nickvergessen** [comment]
That part is handled in a generic way by the notifications app and coming from the activity app.
But in the activity app it's also generic and comes from the actual activity provider.

So you would need to modify the translation string in apps/files_sharing/l10n/ for your languages.
