### ISSUE TITLE
Nextcloud Talk Notifications not being Sent in Certain Cases

### ISSUE THREAD

**Issue by parsmmm** [nextcloud/notifications#1700]
I have a major problem with the Nextcloud notifications section in the Talk section. I have done everything related to allowing the browser and Windows to enable notifications. But why are the notifications not sent in some cases? I have tested this many times between two users. In cases where the user receiving the message has their browser minimized or opens a new tab, sometimes the notification is not sent.

I have tested this on Chrome, Edge, and Firefox browsers and have set the notification access to allow. The Windows version I am using is Windows 10, and all options are active in Settings > Notifications & Actions. I have also checked the Focus Assist settings, specifically the priority section for the browser...

**Comment by nickvergessen** [comment]
> But why are the notifications not sent in some cases?

There is no notification generated by Talk, so the notification app can not send anything.

> In cases where the user receiving the message has their browser minimized or opens a new tab, sometimes the notification is not sent.

It's actually not sometimes but always. It was a design decision to prevent too much noise with mobile apps and desktop clients notifying you, while you are actively chatting in the browser. For more background read https://github.com/nextcloud/spreed/issues/1575

However, good news: The behaviour was changed for the upcoming Nextcloud 28 release of Talk: https://github.com/nextcloud/spreed/issues/1575#issuecomment-1727694865

**Comment by poiNt3D** [comment]
If you want a quick fix: 
https://github.com/nextcloud/spreed/compare/master...poiNt3D:spreed:notifications_notinfocus 
It it will be much noise: i have notifications coming from browser and the desktop app, then both of them but on remote desktop, and the phone.
