### ISSUE TITLE
Notification »Failed to request notifications. Please try to refresh the page manually.« is too technical and erroneous

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#18]
As noted before already, this notification should simply not show. It should only be in the error log. Mostly it shows up in error anyway when the page was timeouted or something similar. It always makes it seem like the instance is broken. Even though there are not even notifications to show most of the time.

It’s a giant papercut. @nickvergessen let’s fix it.

**Comment by MorrisJobke** [comment]
and it shouldn't be there in the first place ... nobody really cares about this, because then also the whole UI doesn't work.

@ChristophWurst also just said that to me.

**Comment by jancborchardt** [comment]
@nickvergessen let’s do this and also backport to stable10!
