### ISSUE TITLE
Feature Request: Send Notification When Server Version is No Longer Supported

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notifications#185]
On Nextcloud 13.0.4

I still receive app update notifications, but at some arbitrary point in the last few weeks my version of Nextcloud became unable to update apps unless I first upgrade my server (with no notification of this given).  It would be very helpful to receive a big old notification that my "stable" server can no longer receive updates rather than learn through trial and error.

How to re-create?
Install 13.0.4
Try to install an app update

**Comment by nickvergessen** [comment]
Well 13 and 12 are still supported officially and receive maintenance updates.
Once 13 goes EOL you should see another notification telling you your server is eol.

**Comment by sunjam** [comment]
I am unable to update any apps in 13.0.4
