### ISSUE TITLE
Desktop notifications are sent out for old notifications

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#192]
Notifications I usually read, but don’t dismiss (x) them. Now just when I checked our cloud.nc instance, I got a notification that

> Roeland invited you to a private conversation

and then after:

> A call started in RailsGirls Summer of Code

Turns out these were the oldest non-dismissed notifications in the list I was getting another notification about.

This should probably not happen. Notifications should be considered "read" when they were seen, and as a result no desktop notifications sent out for that anymore, and the red circle should also not be on the icon anymore. They should still show up in the list though, as reading does not equal dismissing.

What do you think @nextcloud/designers?

**Comment by nickvergessen** [comment]
The HTML desktop notifications only happen on polling, not on the initial loading, so that should be fine in theory, or did this break on the Vue migration?

**Comment by artemanufrij** [comment]
I use Talk for communication with my family. We receive notifications on our different desktops for comments witch are readed a couple hours/days ago.

**Comment by nickvergessen** [comment]
@jancborchardt well I assume it's the desktop clients notification and not from the HTML web notification from the notifications app, so I will close this here, because that is a problem of the sync client:
https://github.com/nextcloud/desktop/issues/685
