### ISSUE TITLE
push-notifications.nextcloud.com - 503 Service Unavailable

### ISSUE THREAD

**Issue by koarlmichael** [nextcloud/notifications#202]
Notification in nextcloud talk not working.

Error notifications in the nextcloud logfile:

GuzzleHttp\Exception\ServerException: Server error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `503 Service Unavailable` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1 (truncated...)

https://push-notifications.nextcloud.com/
Service Unavailable
The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Nextcloud 14.0.4 RC 1
Debian 9
PHP 7.2.12
Apache 2.4.25

**Comment by svankan** [comment]
I have the same problem.
Nextcloud 14.0.3
Ubuntu 18.04.1
PHP 7.2.10
Nginx 1.15.6 with http2 enabled

**Comment by mario** [comment]
Hi,

we're investigating this. 

Cheers,
Mario

**Comment by nickvergessen** [comment]
Nothing to be done on your side, the push server had to be restarted in the end.
If it is still not working for you please post the respective log entries.

**Comment by Bellusterra** [comment]
GuzzleHttp\Exception\ConnectException: cURL error 35: Unknown SSL protocol error in connection to push-notifications.nextcloud.com:443 (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by forum6691** [comment]
Hello
I’ve the last version of Nextcloud 14.04 and Nextcloud talk on my raspberry pi 3 b+ and on my 2 smartphones Samsung S7 edge on android 8.0.0
I have NO SOUND of notification for any text message or any video call on the the 2 phones. 
If I force the videocall on the phone, I can have good communication with video and sound !
I verified system parameters of my andoid application nextcloud talk on the 2 phones. All is OK with notification sound and vibration are normaly activated.

Have you a track to solve this problem ?
Are some log files existing to know where is the problem ?

**Comment by jookk** [comment]
GuzzleHttp\Exception\ServerException: Server error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `503 Service Unavailable` response: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN"> <html><head> <title>503 Service Unavailable</title> </head><body> <h1 (truncated...) 

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 66:

GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensiti ... *")

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 203:

GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 156:

GuzzleHttp\Promise\Promise::callHandler(1, "*** sensiti ... *", [ GuzzleHttp ... l])

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 47:

GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 246:

GuzzleHttp\Promise\TaskQueue->run(true)

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 223:

GuzzleHttp\Promise\Promise->invokeWaitFn()

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 267:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 225:

GuzzleHttp\Promise\Promise->invokeWaitList()

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/promises/src/Promise.php - line 62:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/nc.orencak.eu/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:

GuzzleHttp\Promise\Promise->wait()

/var/www/nc.orencak.eu/lib/private/Http/Client/Client.php - line 231:

GuzzleHttp\Client->request("post", "https://pus ... s", { verify: "/ ... e})

/var/www/nc.orencak.eu/apps/notifications/lib/Push.php - line 143:

OC\Http\Client\Client->post("https://pus ... s", { form_param ... }})

/var/www/nc.orencak.eu/apps/notifications/lib/App.php - line 50:

OCA\Notifications\Push->pushToDevice(797, OC\Notification\Notification {})

/var/www/nc.orencak.eu/lib/private/Notification/Manager.php - line 208:

OCA\Notifications\App->notify(OC\Notification\Notification {})

/var/www/nc.orencak.eu/apps/phonetrack/controller/pagecontroller.php - line 3521:

OC\Notification\Manager->notify(OC\Notification\Notification {})

/var/www/nc.orencak.eu/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OCA\PhoneTrack\Controller\PageController->deleteUserShare("98aa1201ca7 ... 0", "durko")

/var/www/nc.orencak.eu/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OCA\PhoneTra ... {}, "deleteUserShare")

/var/www/nc.orencak.eu/lib/private/AppFramework/App.php - line 118:

OC\AppFramework\Http\Dispatcher->dispatch(OCA\PhoneTra ... {}, "deleteUserShare")

/var/www/nc.orencak.eu/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("PageController", "deleteUserShare", OC\AppFramew ... {}, { _route: "p ... "})

<<closure>>

OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "p ... "})

/var/www/nc.orencak.eu/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { _route: "p ... "})

/var/www/nc.orencak.eu/lib/base.php - line 987:

OC\Route\Router->match("/apps/phone ... e")

/var/www/nc.orencak.eu/index.php - line 42:

OC::handleRequest()

**Comment by rominfo** [comment]
Same problem here, i can't join the push server : push-notifications.nextcloud.com/ 503 Service Unavalaible

**Comment by nickvergessen** [comment]
Sysadmin has been notified, let me reopen and pin this to avoid more duplicates

**Comment by jookk** [comment]
Nextcloud Talk is not reliable, because of not working push server. I have http 400 and curl timeout. Android Talk then freezing.  I think - push server have to be important stable component for Nextclouders :)

**Comment by nickvergessen** [comment]
@mario Talk should not freeze, wenn the proxy is down, can you check?

**Comment by mario** [comment]
@jookk where exactly does it freeze, how do I reproduce?

**Comment by jookk** [comment]
Yesterday, when I wanted to call. App frozen two times.

Dňa 11. marca 2019 8:38:20 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by mario** [comment]
This has nothing to do with push proxy if it really did. Please file a bug on the talk android repo with your OS and phone and I'll see if we have a "freeze" event in the Play Console.

**Comment by jookk** [comment]
Not sent to console, because I downloaded app from github. It doesn't popup 
if I want to send fc

Dňa 11. marca 2019 8:44:15 používateľ Mario Đanić 
<notifications@github.com> napísal:

**Comment by guzzisti** [comment]
Push Notifications were not working yesterday evening, don't know how the state is now:
```
[notifications] Error: GuzzleHttp\Exception\ConnectException: cURL error 7: Failed to connect to push-notifications.nextcloud.com port 443: Connection timed out (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>
from 1.1.1.1 by user at 2019-03-12T19:38:36+00:00
```

anyone experienced this issue?

**Comment by nickvergessen** [comment]
As this requires us to publish our android and ios developer certificate it is not an option atm

**Comment by guzzisti** [comment]
This sounds reasonable. 

I'm not that familiar with android backgrounds: is there a way to completely get rid of Google FCM?
It's a kind of ludicrous to have decentralized platforms like Nextcloud which in the end require the use of centralized services like FCM. Especially as potentatially sensitive information like chats are sent to FCM only for the sake of notifications.

(This is no offense, i understand that things need to be done step by step and till now there was simply no possibility to take this supposedly big step.)

**Comment by parafin** [comment]
Server is unavailable right now. It was also unavailable yesterday around the same time. It interferes with Nextcloud Talk, because starting a call (or adding a user to it) generates a notification and due to big curl timeout this action takes too much time and sometimes fail (at least in the iOS app).

**Comment by guzzisti** [comment]
Push Notifications again not working for me right now. Anyone experiencing the same issue?
Log on the server shows nothing.

**Comment by parafin** [comment]
Works for me right now, didn't work a couple of hours ago. Problems are quite persistent, several hours per day, each day.

**Comment by digititus** [comment]
https://push-notifications.nextcloud.com/ is offline again. No push notifications working

**Comment by nickvergessen** [comment]
Restarted. Should be working again

**Comment by digititus** [comment]
> Restarted. Should be working again

Yes! Thank you

**Comment by digititus** [comment]
And it's down again

**Comment by nickvergessen** [comment]
Fixed

**Comment by jookk** [comment]
Some sort of uptime / connectivity check monitor?

Dňa 24. marca 2019 20:02:29 používateľ Joas Schilling 
<notifications@github.com> napísal:

**Comment by nickvergessen** [comment]
It's in place, we just don't check our work emails too often on our free sunday 🤔

**Comment by jookk** [comment]
Of course :)
And setting cron to automatic reboot server at night?

Dňa 24. marca 2019 22:11:59 používateľ Joas Schilling 
<notifications@github.com> napísal:
