### ISSUE TITLE
push-notifications.nextcloud.com is down

### ISSUE THREAD

**Issue by Fabiosilvero** [nextcloud/notifications#2102]
Hello, 

Https://push-notifications.nextcloud.com is down (along with help.nextcloud.com). 

in nextcloud.log : 
```
cURL error 28: Connection timed out after 30000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications
```

As a result, push notifications are down and 2FA using that with it. Can you please fix it ? 

```
 curl -L -m 10 https://push-notifications.nextcloud.com:443 -v

* Host push-notifications.nextcloud.com:443 was resolved.
* IPv6: 2a01:4f9:2b:29dc::153
* IPv4: 95.217.53.153
*   Trying [2a01:4f9:2b:29dc::153]:443...
* Immediate connect fail for 2a01:4f9:2b:29dc::153: Network is unreachable
*   Trying 95.217.53.153:443...
* Connection timed out after 10001 milliseconds
* closing connection #0
curl: (28) Connection timed out after 10001 milliseconds

```

Also, is there a way to self-host this service ? I only discovered now that 2FA via Nextcloud notification depends on this URL :/ 

Thanks in advance,

**Comment by nickvergessen** [comment]
It's back online, thanks for notifying.

**Comment by webagroprom** [comment]
**ConnectException
cURL error 7: Failed to connect to push-notifications.nextcloud.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://push-notifications.nextcloud.com/notifications**

**Comment by webagroprom** [comment]
**cURL error 7: Failed to connect to www.nextcloud.com port 80: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for http://www.nextcloud.com/
Cannot connect to: www.nextcloud.com**

**Comment by nickvergessen** [comment]
- You already raised a new issue in #2133
