### ISSUE TITLE
Deprecated database schema.

### ISSUE THREAD

**Issue by nicolad** [nextcloud/notifications#236]
Hello @nickvergessen 
Currently I am investigating `App development` documentation and in parallel I am trying to understand how some of Nextcloud apps are being built.
And on v.15 documentation I came accros a chapter https://docs.nextcloud.com/server/15/developer_manual/app/storage/schema.html
which makes me a little bit confused.
From what I understand `database.xml` is not supported in v.15 of the app, but notification app have `min-version="16"` and still uses that deprecated schema.
Please advise me how should I start builing an app from scratch, because `app-tutorial` repo is also  confusing with migration step(which I think is obsolete since a new app has no prior database schema):
https://github.com/nextcloud/app-tutorial/blob/refresh/lib/Migration/Version1000Date20181126200057.php
Thank you.

**Comment by nickvergessen** [comment]
You can have a look at the activity app:
https://github.com/nextcloud/activity/blob/master/lib/Migration/Version2006Date20170808154933.php

To create a new migration for your app, simply run the following command from within your nextcloud folder: (replace APP with your appid e.g. notifications, and XXXYYY with the version e.g. notifications is at 2.4.0, then you use `2004` for XXXYYY) `occ migration:generate APP XXXYYY`

database.xml is still working, but yeah I should upgrade this app to migrations too.

For the first migration you can use `occ migration:generate-from-schema APP XXXYYY` to translate the database.xml to a migration.
