### ISSUE TITLE
Support icons in notifications

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#25]
@nickvergessen as we talked about. When there are more notifications, they should be able to show icons. In the beginning it could simply be the app icon, or for example the share icon for approving shares or federated shares.

(As said, the web notifications API also supports icons – see our usage in the Mail app – so it shouldn’t be an issue.)

**Comment by nickvergessen** [comment]
Icons need to be full URL. See:
https://developer.mozilla.org/de/docs/Web/API/Notification/icon

**Comment by jancborchardt** [comment]
Is there a problem with that? Cause it can be built with the base URL and the app folder, no?

**Comment by nickvergessen** [comment]
No, this was a pure informative comment for the future, so I have all the info in one quick place.

**Comment by nickvergessen** [comment]
API change has been merged: https://github.com/nextcloud/server/pull/1660
