### ISSUE TITLE
PROPFIND /dav/systemtags/ 500 (Internal Server Error)

### ISSUE THREAD

**Issue by fossxplorer** [nextcloud/notifications#26]
Using NC stable10, notifications gets in the way for file access control giving the error provided in subject in the dev console. File access control GUI spins for ever. Disabling notifications fixes it.

I can provide more details later :)

@nickvergessen

**Comment by nickvergessen** [comment]
More details would be awesome @fossxplorer , since it works perfectly fine here on my end.
Also I would not know, how the notification app breaks the dav system tags endpoint.

The access control GUI spins because of the missing tags. So that is "solved"

**Comment by fossxplorer** [comment]
Yes, i can't reproduce it anymore. Closed.
