### ISSUE TITLE
Richer notification messages for comment mentions (and other notifications)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#27]
As mentioned in https://github.com/nextcloud/server/pull/1449#issuecomment-251992359:
Regarding the UI of the comment mention notification, it needs to be enhanced like this:

> 😎 Joas mentioned you in a comment on 🖼 **Berlin Weißensee at night.jpg**

Smiley is a placeholder for the avatar, and image for the filetype. Remember that usernames need to _always_ have avatars next to them. And ideally filenames should always have a connection to their filetype icons or previews.

Otherwise we just have bland text here which is a drag to use and takes long to read. Images and highlighting is very important here for visual clarity and quick understanding.

cc @nickvergessen @blizzz

**Comment by nickvergessen** [comment]
Well the problem is that we want to be compatible with the web and system notifications. Not sure if they support any kind of markup. But if they do, sure, why not.

**Comment by nickvergessen** [comment]
After some search, desktop and HTML5 notifications both only allow plain text.

We could introduce a second string version which includes markup. But we basically run into the same problem, we already faced with the activities. They are also shown in the client, and maybe one day the android app also has a notification list built in (not only using the android notifications). I'm quite sure that they can **not** use HTML.

I do not want to add three versions of all strings to the endpoint to match all their needs.

**Comment by jancborchardt** [comment]
I understand we need to habe a plain text version for the system notifications.

But that should not be our lowest common denominator. Especially since we control the desktop and mobile apps it should definitely be possible to include avatars, bolding, filetype icon, and stuff like tappability of file to show it. 

Any reason this could not be possible? cc @tobiaskaminsky @AndyScherzinger @rullzer

**Comment by AndyScherzinger** [comment]
@jancborchardt none that I know of, anything you described above should possible to implemented on Android :smiley:

**Comment by nickvergessen** [comment]
Well we already failed to find a good solution for the activity API.
Maybe we should have a common OCS Markdown or something like that. Then again I don't feel too comfortable just guessing what we want to do. Should discuss this best in person. Maybe at the Nextcloud11 hackathon.

**Comment by AndyScherzinger** [comment]
Erm, well from an Android perspective it would be better to "simply" have a UI definition with data to be put in each of these elements, since you don't have standard notifications with markdown/-up rendering for notification. You rather have different UI elements with different styling where we would put the data into :)

**Comment by nickvergessen** [comment]
So basically something like:
```json
[
  "{param1} mentioned you in a comment on {param2}",
  {
    "param1": {
      "object_type": "user",
      "object_id": "test",
      "object_name": "Test Mustermann"
    },
    "param2": {
      "object_type": "file",
      "object_id": 42,
      "object_name": "file.txt",
      "object_fullname": "path\/to\/file.txt"
    }
  }
]
```
?

We can do something like that. But then we need to find list all the supported types somewhere, and define a sane behaviour for unknown object types, but sure.
I would then also use the same system in the activity app, so app developers only have to write one "parser" instead of multiple ones.

**Comment by AndyScherzinger** [comment]
Well, kind of. @nickvergessen's proposed text+placeholders would work for us since we could then do a smarter replacement in adding our Android-platform specific styling (as in how this needs to be applied technically).

**Comment by jancborchardt** [comment]
Seems good. If the relevant info can be extracted from that like:
- user avatar
- link to user which we possibly use in the future (like for profile hovercards)
- file type icon or preview
- link to file to be able to directly navigate there
