### ISSUE TITLE
[Question] Sending a notification to another user

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#287]
Is it possible to send the notification to another cloud user? In cloud service I can run the URL in GET or POST method. After that user are receiving the notification with the specified context which is contained in the URL. If yes then how to correct construct the link? How the link will be constructed correctly? Currently I'm sending notifications to another application using below URL where X is the ApiKey value:

`https://www.webpage.com/push?ApiKey=XXXXXXXXXXXXXXXXXXX&PushTitle=Title&PushText=Message text`

Thanks and have a nice day!

**Comment by nickvergessen** [comment]
Admins can do that as shown at https://github.com/nextcloud/notifications/blob/master/docs/admin-notifications.md
