### ISSUE TITLE
No push notification on app update

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notifications#305]
It seems to be very related to #226, but it is still a bit different

- setup a group to be notified for app updates (e.g. "appUpdates")
- add admin and a non-admin user to this group
- wait until an app update pops up
	- see it in web ui (notification icon)
	- see it in notification list for non-admin user (in android app)
	- note that push notification is missing

**Comment by nickvergessen** [comment]
Or more likely due to https://github.com/nextcloud/notifications/issues/202

The problem with that one has been identified...
