### ISSUE TITLE
Nextcloud shows Owncloud update notification 

### ISSUE THREAD

**Issue by caco3** [nextcloud/notifications#32]
Nextcloud shows me an update notification but seems still to refer to Owncloud:
![nextcloud](https://cloud.githubusercontent.com/assets/1783586/19783216/568665b6-9c91-11e6-9259-1f8bc76b4bcc.png)

![screenshot_20161027_220559](https://cloud.githubusercontent.com/assets/1783586/19783279/9f7b28ba-9c91-11e6-8b40-f43bcd9d3c0b.png)

Version: Nextcloud 10.0

**Comment by LukasReschke** [comment]
https://help.nextcloud.com/t/notification-about-an-upgrade-to-owncloud-9-1-1-in-nextcloud-10-stable/4573

**Comment by nickvergessen** [comment]
Also @caco3 this light-blue bar is not from the notification app, but from the server itself.
