### ISSUE TITLE
I'm receiving notifications for shares i canceled.

### ISSUE THREAD

**Issue by kas70** [nextcloud/notifications#33]
### Steps to reproduce
1. Set up 2 accounts A and B.
2. From within A share a folder with B. Put some files in the folder.
3. If B enabled notifications in the settings, notifications will be send to B, if A adds files to the shared folder.
4. Now let B cancel the share.
5. The folder will disappear in account B.

### Expected behaviour
B should not receive email notifications, if A now adds files.

### Actual behaviour
B receives email notifications.

### Server configuration
**Operating system**:
Debian 8.6
**Web server:**
nginx 1.6.2
**Database:**
MySQL
**PHP version:**
5.6.27
**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (stable)
**Where did you install Nextcloud from:**
https://nextcloud.com/install/
**Signing status:**
No errors have been found.

**Comment by nickvergessen** [comment]
This email is from the activity app.
Also the email is from the past, and the activity app can not know that the file doesn't exist anymore.
So this can/will happen for the first activity email you receive after canceling the share

**Comment by kas70** [comment]
> This email is from the activity app.

Ok, i'll open an issue in the activity repo.

> Also the email is from the past

No, this also happens for new files, which are added weeks later after canceling the share.
