### ISSUE TITLE
Allow Notification URLs to be selectable

### ISSUE THREAD

**Issue by sunjam** [nextcloud/notifications#343]
It would be very helpful if public url links in notifications could be selected / directly copied from the notification.

Example Notification:

You were just updated to Nextcloud 16.0.1 and you can read the release notes at [https://www.example.com](https://www.example.com)

**Comment by nickvergessen** [comment]
Can you make a screenshot to clarify which notification you are talking about?

**Comment by sunjam** [comment]
> Can you make a screenshot to clarify which notification you are talking about?

![1561220179](https://user-images.githubusercontent.com/1787238/59966255-a7bf0b80-94ce-11e9-9386-9f8f9aeb0e3f.png)

**Comment by nickvergessen** [comment]
I'm still unsure from which app that message is.
Can you run `occ app:list` and post the result?

**Comment by githubkoma** [comment]
I would be interested in this as well..
I am currently trying to develop my own little nextcloud webapp according to the [Documentation](https://docs.nextcloud.com/server/15/developer_manual/app/index.html).
In the future that app also should send Notifications to users..

Referring to @sunjam , those notifications could perhaps also contain a url, like: https://nextcloud.xyz.org/apps/myApp/#entry=123.

A way to have to "somehow open" those URLs would be great
Is this even possible anyhow?

Or do you see any other possibility to have the notification itself directly link to the mentioned webpage?

**Comment by jancborchardt** [comment]
Totally agree here, woud be cool to be able to click links to have them open in a new tab. :) 

For example if I get a link via Nextcloud Talk, on the desktop I can actually click the link in the notification. In the web interface it’s not clickable:
![Ability to click links in notifications](https://user-images.githubusercontent.com/925062/62781802-09582b00-bab9-11e9-8ab0-ee18ffcc4791.png)

**Comment by nickvergessen** [comment]
That is actually a total different issue, please create a new one for that.

I will close this issue for now, because the "NextcloudPi update" notification has no known origin and can therefor not be fixed for now.

**Comment by githubkoma** [comment]
> > Can you make a screenshot to clarify which notification you are talking about?
> 
> ![1561220179](https://user-images.githubusercontent.com/1787238/59966255-a7bf0b80-94ce-11e9-9386-9f8f9aeb0e3f.png)

the creator of the app that produces this notification has to implement it him-/herself..

the field "link" in the $notification-object has to be filled, per example: https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v2.md
