### ISSUE TITLE
Push notification with XMPP, MQTT

### ISSUE THREAD

**Issue by RabbitDuck** [nextcloud/notifications#344]
Hi,

As far as I know, the push notification of Nextcloud uses Google service. As we want to go without google completely, it is possible to use XMPP for sending and receiving notification from Nextcloud? So that if there is any activity or admin notification, we can have XMPP message popup on our phone instead of email or notification push. 

We already setup our own XMPP server (ejabberd) and the newest version of it supports MQTT. May be we can make use of MQTT for notification.

Thanks!

**Comment by nickvergessen** [comment]
@mario another idea

**Comment by nickvergessen** [comment]
@RabbitDuck I'm closing this, as this app repo is not the right place for this discussion.
