### ISSUE TITLE
No function "Dismiss all notifications"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#345]
### Expected behaviour
Ability to delete all notifications.

### Actual behaviour
You can not delete all notifications from not displaying the function: "Dismiss all notifications".

![obraz](https://user-images.githubusercontent.com/47037905/58558220-872dc980-8220-11e9-81a6-6d3c24cc4d74.png)

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.1

**App:**
Notifications 2.4.1

### Client configuration
**Browser:**
Firefox 67.00
Opera 60.0.3255.109

**Operating system:**
Win10

**Comment by nickvergessen** [comment]
The entry should appear as soon as you have more than 2 notifications.

But somehow the inner div of the transition group is not showing. Can you help @skjnldsv 

https://github.com/nextcloud/notifications/blob/f41cfbf3f737121d9bd4de384a70bd204442b5a9/src/App.vue#L23-L26
