### ISSUE TITLE
button of "help improve Nextcloud" notification overlap the notification below 

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/notifications#362]
![image](https://user-images.githubusercontent.com/22591354/60101535-385e4b80-975c-11e9-9dbf-1ca539b87ca2.png)

### Steps to reproduce
1. have a notification below the "help improve nextcloud" one
2. see the buttons of the first one overlap the second one

### Server configuration
**Nextcloud version:** 16.0.1

**Comment by nickvergessen** [comment]
Fixed with #388
