### ISSUE TITLE
Feature request - Create notification with Client

### ISSUE THREAD

**Issue by erosinger** [nextcloud/notifications#378]
Just like reading and deleting notifications with a Client (see https://github.com/nextcloud/notifications/blob/master/docs/ocs-endpoint-v1.md) there should be a way to create notifications with a client.

This would allow other 3rd party applications to integrate into Nextcloud and make it suitable to display further notifications to users. In a scenario where Nextcloud is embedded in a broader ecosystem, Nextcloud can become the core application for it by this.

e.g. "In order to get a single notification, you can send a POST request against /ocs/v2.php/apps/notifications/api/v1/notifications/"

**Comment by nickvergessen** [comment]
There is https://github.com/nextcloud/notifications/blob/master/docs/admin-notifications.md

It only works for admins, but you can create a dummy account for it...
