### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by tikoflano** [nextcloud/notifications#405]
Do notifications appear as desktop notifications too? At least I don't get them even though I have them enabled in my browser and I also have the desktop app.

**Comment by nickvergessen** [comment]
Should work again with nextcloud 16.0.3

**Comment by tikoflano** [comment]
I'am using v16.0.3

It is deployed using Docker, maybe that matters?

**Comment by nickvergessen** [comment]
The desktop notifications from the browser only show, when they appear while Nextcloud was open in the background. Additionally you have to accept the permission request once when it happens for the first time.

Or do you mean from the sync client?

**Comment by tikoflano** [comment]
I mean the ones from the browser and I have accepted the request. Does it need to be the active tab when the notification appears? Or it can be one of the other opened tabs?

**Comment by nickvergessen** [comment]
Any tab should be sufficient
