### ISSUE TITLE
Empty $data['subject'] [bug]

### ISSUE THREAD

**Issue by CezaryGoralski** [nextcloud/notifications#413]
Hello you have bug in triming notifications subjects at notifications/Push.php 
https://github.com/nextcloud/notifications/blob/73bdc21c75af16f46a3e487b2cf8a8bb9d89fa6d/lib/Push.php#L268
`if (strlen($subject) > $dataLength) {
			$data['subject'] = substr($subject, 0, $dataLength) . '…';
		}`

and it should be 
`if (strlen($subject) > $dataLength) {
			$data['subject'] = substr($subject, 0, $dataLength) . '…';
		}else{
	$data['subject'] = $notification->getParsedSubject();
}`
because otherwise when the parsedSubject length will be less than 255 the $data['subject'] field is gona be empty

**Comment by nickvergessen** [comment]
Arg, of course... that Is why I got the empty notifications.

Thanks for the pointers
