### ISSUE TITLE
Icon alignment is a bit off

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notifications#42]
https://github.com/nextcloud/server/pull/2383#issuecomment-263319674

The problem is, should it be aligned for 1 lines, for 2, just centered or ...

@jancborchardt any idea?

**Comment by schiessle** [comment]
I would suggest to center it to the text on the right side

**Comment by jancborchardt** [comment]
To make it consistent-looking with varying lengths of text, we should display it at a certain height. I agree with Björns comment on the other issue that the icon should move a bit down to appear centered with the text. That’s basically aligning for 2 lines. And that margin-top can then be used as general style.
