### ISSUE TITLE
Stop Ads in notifications

### ISSUE THREAD

**Issue by Luticus** [nextcloud/notifications#426]
I need to know how to prevent notification ads like this:  
![notificationAD](https://user-images.githubusercontent.com/7807109/64143031-66a37b80-cddc-11e9-90fb-926fbaf9cb6c.png)

I should not be seeing ads in my server's notification feed.  This kind of stuff should be reserved for opt-in email or some such.  I sincerely hope that these kinds of messages aren't making it to my normal users, otherwise I'll have to yank the entire notification system out.  I'm rather disappointed to see this kind of thing personally.  I didn't see anywhere that you guys would be injecting ads into nextcloud.  I'm curious where this notification came from and how it got in the feed in the first place.  Does this mean that your servers have the ability to push information to my servers?  I hope not, because that runs counter to my ideals of a self contained system.

**Comment by Luticus** [comment]
I have disabled notifications until this matter is resolved.

**Comment by nickvergessen** [comment]
It's only been sent to administrators by default.

Just as a short reply, I will post a follow up in some minutes

**Comment by nickvergessen** [comment]
# Disbaling the notifications or changing the target group

The notifications are by **default only send to administrations**. You can change the group in Settings > Administration > Basic settings > Nextcloud announcements

> ![Bildschirmfoto von 2019-09-03 08-32-41](https://user-images.githubusercontent.com/213943/64149585-895a8200-ce26-11e9-87e0-b8f188698060.png)

If you don't want to have this at all, you can simply disable the `Nextcloud announcements` app in Apps > Enabled apps > Nextcloud announcements

> ![Bildschirmfoto von 2019-09-03 08-32-57](https://user-images.githubusercontent.com/213943/64149650-bdce3e00-ce26-11e9-9d69-2a6b212ed07d.png)

# General note

1. Please note that we are not selling "ads" or placing "ads" in your notifications or anywhere else in your Nextcloud. The nextcloud announcement feature was put in place quite some time ago and this is only the 3rd message we put it in those 3 years it has been in place.

2. "Does this mean that your servers have the ability to push information to my servers?" - No, similar to the update check your Nextcloud fetches the information from our server. You can easily stop this as mentioned above by disabling the "Nextcloud announcements" app.

3. "Are there more things communicating with your servers?" - In fact there are 3 features communicating with Nextcloud servers:
    * Check for updates (**Opt-Out**, Option: disable the "Update notification" app)
    * Generic usage stats (number of files, shares, …, php version, database system) (**Opt-In**, Option: disable the "Usage survey " app or don't check the "Send usage survey monthly" box)
    * The nextcloud news (this issue) (**Opt-Out**, Option: disable the "Nextcloud announcements" app)

**Comment by nickvergessen** [comment]
> I have disabled notifications until this matter is resolved.

@Luticus as written above, you can reenable the notifications app and instead either disable the nextcloud announcements app, or be okay with this ~1 notification/year from Nextcloud. Sorry if you got the feeling of having your ideals hurt. You may check our prinicipals and our mission at https://nextcloud.com/blog/the-nextcloud-mission-and-principles/ and see if it matches your expectations. If you still think there is something to discuss, feel free to post a reply on the blog post or drop an email to `<my github name>@nextcloud.com` or `jos@…`

**Comment by Luticus** [comment]
I appreciate your response to this and will try the methods you have suggested. 

I meant no offense, if you guys want to put ads in your product that's your business, I guess I just don't like surprises like that.  As long as there's a way to prevent that in the future I'm more than happy to keep using Nextcloud, which is up there on the list of best pieces of software ever written.  I'm also relieved that it is likely that my other users aren't seeing these messages.  

Also I understand that you are not selling or placing ads, however first party ads are still ads in my opinion.  Even if that conference was free (it's not) you're still advertising it in the notifications.  I get that not everyone will see it that way, but that's my opinion on the subject.  To be fair, the notification was pretty benign.  I'm also happy to know about said conference, I would just prefer to get an email on it instead.  I actually attend conferences like this all the time, but in this case it's a bit far away and I'm kinda booked up for travel right now.  

Anyway, again, I do appreciate your reply and will look in to it.  I apologize if anyone took offense to anything I said in my original statement.  I guess I'm just passionate.  :)

**Comment by matthewbloch** [comment]
My annoyance was more that Windows notified me of the 2019 conference daily until today! I got found this bug report, realised I had to log into the web interface (which I do v rarely) to disable it. Just acknowleding the notification in Windows wasn't enough, which seems counter-intuitive.
