### ISSUE TITLE
Icons in notifications

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/notifications#43]
For example in this update notification – shouldn’t the spreed app icon be shown automatically because it concerns a specific app?
![capture du 2016-11-30 14-53-53](https://cloud.githubusercontent.com/assets/925062/20754793/e6491b54-b70c-11e6-8ee3-da6b8dfa1e24.png)

cc @nickvergessen

**Comment by nickvergessen** [comment]
well but the notification app doesn't know the image name of the other app, some use the appid, some `app`, some app-dark, ...

I guess we should just use a generic icon for updates in general. Any idea?

**Comment by jancborchardt** [comment]
There’s only two things apps use: Either app.svg or `appname`.svg, so it’s very easy to get. Of course the color has to be reversed just like we do for the menu and apps mgmt. cc @juliushaertl is there any class or generic documented mechanism to use for this?

> I guess we should just use a generic icon for updates in general. 

No, that defeats the purpose of having icons.

**Comment by nickvergessen** [comment]
Well but an update notification on android also shows withe the playstore icon, not with the app that receives an update.
I'd say the video call icon should be for video calls only, not for app updates of the app....
Anyway...

**Comment by jancborchardt** [comment]
Good point. Showing the plus icon of »Apps« would be a bit strange here though. :\

@nickvergessen btw is it possible to have a button directly there to »Update app« which triggers it from there?

**Comment by nickvergessen** [comment]
> btw is it possible to have a button directly there to »Update app« which triggers it from there?

This is not really possible, because the user receiving the notification might not be an admin. Also I don't want to risk someone breaking their instance because they updated an app via their desktop sync client or something. The notification is clickable and brings you to the page with the update button. So that should be okay for now. If we are more risk friendly in the future we can try it for 12 or something.

**Comment by juliushaertl** [comment]
@jancborchardt There is no automatic icon inversion. It is always done by adding svg filters, see https://github.com/nextcloud/server/blob/master/core/templates/layout.user.php#L115-L118 for details.

**Comment by jancborchardt** [comment]
> This is not really possible, because the user receiving the notification might not be an admin.

What do you mean by that? Don’t only admins get that update notification? It’s completely irrelevant for regular users as they can not update it.

**Comment by nickvergessen** [comment]
No, of course not. But admins can pick another group to receive the notifications, because in most cases the admin user is not used to sync files, but to manage the instance only, so they neither log in regularly nor are notified in their sync client.

**Comment by jancborchardt** [comment]
@nickvergessen but then couldn’t we easily show the »Update app« button based on if you are an admin? It would be really handy to not need to go in the apps menu but make the notification interactive. If everything goes smoothly then that is the superior flow. If there’s an issue we can still redirect to the apps mgmt page.
