### ISSUE TITLE
Unformatted text and no spaces

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#435]
The content in the notifications is hard to read:
1. No space between words.
2. Unformatted message text.

English version:
![obraz](https://user-images.githubusercontent.com/47037905/64486308-d5913200-d22b-11e9-8761-5a816d92f6e0.png)

Polish version:
![obraz](https://user-images.githubusercontent.com/47037905/64486314-f8bbe180-d22b-11e9-903b-a8b642849f5e.png)

A similar topic about the lack of a space character was raised in the issue on [Spreed ](https://github.com/nextcloud/spreed/issues/2152).

**PHP version:**
7.2.14

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Notifications version:**
2.4.1

### Client configuration
**Browser:**
Firefox 69.0

**Operating system:**
Win10

**Comment by nickvergessen** [comment]
This was already fixed with https://github.com/nextcloud/notifications/pull/420
And eill be part of 16.0.5
