### ISSUE TITLE
Show date/time on notifications

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/notifications#46]
As per nextcloud/spreed#162 by @schiessle 

@jancborchardt can you draw something for this? should be top left of the notification, next to the delete icon?

**Comment by jancborchardt** [comment]
Yes, top right (I assume you meant that) basically exactly the same as for the sidebar comments & activity list. Maybe you can even use the HTML/CSS straight from there because it’s a similar format.

**Comment by jancborchardt** [comment]
(If you make a work-in-progress pull request I can adjust the rest.)

**Comment by nickvergessen** [comment]
PR is in #47
