### ISSUE TITLE
Improve visual experience of federated shares

### ISSUE THREAD

**Issue by schiessle** [nextcloud/notifications#478]
At the moment it looks like this if I receive a federated share:

![image](https://user-images.githubusercontent.com/1589737/69065793-913ac300-0a20-11ea-87c6-dadc576faa01.png)

As most of the time the user don't care about the federated cloud id and it often looks quite technical I would suggest to only show it on hover over the display name.

cc @nextcloud/designers

**Comment by ma12-co** [comment]
I agree @schiessle, but can't we just omit the id and use the display name only?

>I would suggest to only show it on hover over the display name.

What do you have in mind here? I would avoid displaying a tooltip over another tooltip..

**Comment by nickvergessen** [comment]
Why "over another tooltip" i guess its fine here

**Comment by ma12-co** [comment]
I mean, visually the notifications popover and the tooltip would be the same element, and in this case they would be nested.. Maybe that can look a bit odd?? But yeah if it's mandatory to see the federated cloud id in the notification we should go for it!

**Comment by jancborchardt** [comment]
@ma12-co We use tooltips in the Contacts menu too, which is a popover as well. Don’t think this is a real issue. :)

Agree with @schiessle on removing the Federated Cloud ID and showing it only on hover.
Also, it says "as a remote share" – don’t we say "as a federated share"?

(I do think it is good to state at least something so it’s distinguished a bit from same-cloud shares, be it simply for security reasons.)
