### ISSUE TITLE
Wrong url at app update notification

### ISSUE THREAD

**Issue by Wuppie007** [nextcloud/notifications#48]
There was an update from the contacts app, but the url where is pointed to is the local ipadress and not the domain.

from the firefox editor:
a href="https://192.168.0.123/index.php/settings/apps#app-contacts" class="notification-subject"

### Expected behaviour
Change the 192.... url to the domain

**Comment by nickvergessen** [comment]
Fix your config.php `overwrite.cli.url` ;)
