### ISSUE TITLE
The upgrade Nextcloud to 16.0.6 is disabling push-notifications for nextcloud-talk on android

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/notifications#488]
The upgrade to 16.0.6 (16.0.5) is disabling push-notifications for nextcloud-talk on android

### Server configuration

**Operating system**: Ubuntu 18.04.3 LTS

**Web server:** Apache/2.4.29

**Database:** PostgreSQL 10.10

**PHP version:** 7.2.24

**Nextcloud version:** (see Nextcloud admin page) 16.0.4.1

fresh install
No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - circles: 0.17.8
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - deck: 0.6.6
  - dropit: 0.3.0
  - event_update_notification: 0.3.4
  - extract: 1.2.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_antivirus: 2.2.0
  - files_ebookreader: 0.0.1
  - files_external: 1.7.0
  - files_frommail: 0.3.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.1.4
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.11.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - ransomware_protection: 1.4.0
  - recommendations: 0.4.0
  - richdocuments: 3.4.3
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - sharerenamer: 2.7.2
  - social: 0.2.101
  - socialsharing_email: 1.0.6
  - spreed: 6.0.4
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.3
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - uploaddetails: 0.1.2
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - encryption

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "homelk.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "production",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 0
        },
        "default_language": "ru",
        "default_locale": "ru_RU",
        "logtimezone": "Europe\/Moscow",
        "log_rotate_size": 104857600,
        "session_lifetime": 7200,
        "remember_login_cookie_lifetime": 600,
        "session_keepalive": true,
        "has_internet_connection": true,
        "defaultapp": "files",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app.mail.accounts.default": {
            "email": "%USERID%@example.mail.com",
            "imapHost": "example.mail.com",
            "imapPort": 143,
            "imapSslMode": "tls",
            "smtpHost": "example.mail.com",
            "smtpPort": 587,
            "smtpSslMode": "tls"
        }
    }
}

Android 9
Nextcloud-talk v7.0.8

**Comment by kesselb** [comment]
Could you test the patch and report back? ;) I'm sure that patch fix `TypeError: Argument 1 passed to ` but probably not the disabled push-notifications.

**Comment by IamLuksha** [comment]
I also do not receive notifications on the phone, but after updating from 16.0.6 to 17.0.1

**Comment by lvarnava** [comment]
@kesselb thank you for responding to my problem.
I tested the patch - there were no errors.
but bug with  push-notifications doesnt fixed.

**Comment by kesselb** [comment]
> [notifications] Fatal: error:0E06D06C:configuration file routines:NCONF_get_string:no value
POST /ocs/v2.php/apps/spreed/api/v1/chat/rfoov99r

cc @nickvergessen something for talk?

**Comment by nickvergessen** [comment]
> something for talk?

No. But well, when your `oc_notifications_pushtokens` is empty, we canm of course not push anymore. Try removing the account and re-authenticate

**Comment by lvarnava** [comment]
Did it more than once - the same problem.

**Comment by nickvergessen** [comment]
Is the notification app still enabled? Did an entry appear in the table and then get deleted on a chat message?

**Comment by nickvergessen** [comment]
Do your users have the files `private` and `public` in `data/appdata_RANDOMPART/identityproof/user-THEIRUID/` ?

**Comment by lvarnava** [comment]
yes they have

**Comment by vincowl** [comment]
Hi,
I solved by removing every entry in `oc_notifications_pushtokens` and deleting/recreating users in the android app. Works with nextcloud 17.0.1 now

**Comment by lvarnava** [comment]
Hi everyone!
In my case with NC16.0.6 does not work.
Even if you succeed, it is not happy.
I have up to 1000 users and I will have to explain to them how to revoke access for nc-talk-android and re-authenticate.
And this is just after another update in "production"!

And I tried to roll back to 16.0.4 and the push-notifications works stably.

**Comment by vincowl** [comment]
@lvarnava Fully agree with you, it was just a trick but itis necessary to get a clean correction.

**Comment by nickvergessen** [comment]
So 16.0.4 works for you but 16.0.6 does not?

**Comment by lvarnava** [comment]
Of course, I wrote that the update breaks the push-notifications.
> The upgrade to 16.0.6 (16.0.5) is disabling push-notifications for nextcloud-talk on android

**Comment by lvarnava** [comment]
Tested on two servers with different providers.

**Comment by nickvergessen** [comment]
There are hardly any difference between 16.0.4 and 16.0.6
The only change that could cause it is:
https://github.com/nextcloud/notifications/compare/v16.0.4...v16.0.6#diff-1383a847921c5d9a7163f3de431d5165

The problem is in 16.0.4 we didn't set any subject in case the subject is below a certain threshhold, above that threshhold we trim it to the possible max length.
Can you try if remove line 201 `$data['subject'] = $subject;` fixes the issue for you?

If so please replace the line with:
```php
$data['subject'] = substr($subject, 0, 5);
```
then try
```php
$data['subject'] = substr($subject, 0, 10);
```
and so on, until it does boom.
Then tell me the number you used last before it did boom.

**Comment by lvarnava** [comment]
>Can you try if remove line 201 $data['subject'] = $subject; fixes the issue for you?

it worked!

**Comment by lvarnava** [comment]
>$data['subject'] = substr($subject, 0, 5);

did not work

>$data['subject'] = substr($subject, 0, 10);

it worked!

**Comment by nickvergessen** [comment]
That makes no sense. The number should grow and at some point you should get the error. Please always try with the same chat message to be sure, because the size matters.

**Comment by lvarnava** [comment]
$data['subject'] = substr($subject, 0, 90);

[notifications] Fatal: error:0909006C:PEM routines:get_name:no start line

POST /ocs/v2.php/apps/spreed/api/v1/chat/nur38cue

**Comment by lvarnava** [comment]
while moving to this value, the push-notifications did not work for some values

**Comment by nickvergessen** [comment]
Are you by chance using any multibyte based language (chinese, japanese, russian, …)?
Because it looks after some quick math it looks like the following:

* Notifications are limited to 255 characters
* Overhead is around 70-80 characters
* Available chars: 255 - 80 = 175

If I half that, I come to around 90 which is where it breaks for you.

**Comment by lvarnava** [comment]
I use the Russian language

**Comment by nickvergessen** [comment]
Can you check if the following change fixes it:
https://github.com/nextcloud/notifications/pull/496/files

**Comment by lvarnava** [comment]
https://github.com/nextcloud/notifications/pull/496/files
did not work

I don’t think that the problem is with the language.
I sent only numbers in the message or called, I get the same effect.

surprising but
>$data['subject'] = substr($subject, 0, 10);

it works!

**Comment by lvarnava** [comment]
after upgrading to 16.0.8 push-notifications still do not work for me.

but everything works with this code:

```
// Max length of encryption is 255, so we need to shorten the subject to be shorter
                $subject = $notification->getParsedSubject();
                // Half the length for multibyte characters like Russian, Chinese, Japanese, Emojis, …
                $dataLength = 245 - strlen(json_encode($data));
                if (strlen($subject) > $dataLength) {
                $data['subject'] = substr($subject, 0, $dataLength) . '…';
                } else {
                $data['subject'] = substr($subject, 0, 10);
                }
```
