### ISSUE TITLE
Notification app needs lot of RAM and Processes under NC17.01 

### ISSUE THREAD

**Issue by Bolli84** [nextcloud/notifications#491]
# Steps to reproduce
1. Update to NC 17.0.1 and PHP 7.2.24 or PHP7.3.11
2. Activate Notifications 
3. Use Notifications e.g. Talk, ...

### Expected behaviour
Notification pops up and is used normally

### Actual behaviour
Notification pops up
Server memory and process count increases until it fills all memory (16gb)
After deactivating the notification app, verything is freed up. 
Activate app again and wait until more notification come in.

**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.2.24 & 7.3.11
**Nextcloud version:** (see Nextcloud admin page)
17.01

**Comment by lutoma** [comment]
Same, this brought down our production instance. Upon closer inspection it seems the Nextclout client is spamming hundreds of requests a second to `DELETE /ocs/v2.php/apps/notifications/api/v2/notifications/8 HTTP/2.0`

**Comment by Bolli84** [comment]
Looking into it, I have exactly the same, but cannot say if that is the issue.

**Comment by nickvergessen** [comment]
> Upon closer inspection it seems the Nextclout client is spamming hundreds of requests a second to 

@nextcloud/desktop can you check this? you should only send 1 delete request per notification?!

**Comment by nickvergessen** [comment]
Fixed by https://github.com/nextcloud/ios/pull/1031
