### ISSUE TITLE
Cannot Dismiss notifications

### ISSUE THREAD

**Issue by sirohiparag** [nextcloud/notifications#530]
### Steps to reproduce
1. Login to NC install click on the notification bell icon
2. Click on the X sign next to each notification to dismiss a specific notification.
3. Scroll to the bottom of the notifications and click on Dismiss all notifications.

### Expected behaviour
It should dismiss either the specific notification or all depending on what was clicked out of step 2 or step 3 above.

### Actual behaviour
A small message appears saying Failed to dismiss notification. 

## Server configuration detail

**Operating system:** Linux 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 10.1.43

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, pspell, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, xmlrpc, Zend OPcache

**Nextcloud version:** 17.0.2 - 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Nextcloud Webiste

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.10.1
 - announcementcenter: 3.6.1
 - apporder: 0.9.0
 - calendar: 1.7.2
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - deck: 0.7.0
 - federatedfilesharing: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.21.1
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - provisioning_api: 1.7.0
 - quicknotes: 0.2.2
 - ransomware_detection: 0.6.0
 - ransomware_protection: 1.5.1
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.2
 - tasks: 0.11.3
 - text: 1.1.1
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - workflowengine: 1.7.0
Disabled:
 - accessibility
 - admin_audit
 - encryption
 - federation
 - files_external
 - files_rightclick
 - files_videoplayer
 - firstrunwizard
 - gallery
 - nextcloud_announcements
 - ojsxc
 - password_policy
 - passwords
 - privacy
 - recommendations
 - support
 - survey_client
 - systemtags
 - theming
 - user_ldap
 - viewer

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "team.myurl.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.2.1",
    "overwrite.cli.url": "https:\/\/team.myurl.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "team",
    "loglevel": 2,
    "maintenance": false,
    "default_language": "en",
    "default_locale": "en_IN",
    "defaultapp": "mail",
    "overwriteprotocol": "https",
    "knowledgebaseenabled": false,
    "allow_user_to_change_display_name": true,
    "auth.bruteforce.protection.enabled": true,
    "integrity.check.disabled": true,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "ojsxc"
    ],
    "mail_smtpmode": "sendmail",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Google chrome console:

xhr.js:172 DELETE ocs/v2.php/apps/notifications/api/v2/notifications/326 412 (Precondition failed)
xhr.js:172 DELETE ocs/v2.php/apps/notifications/api/v2/notifications 412 (Precondition failed)

globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
He @ globals.js:26
i @ globals.js:38
parseMessage @ richObjectStringParser.js:31
renderedMessage @ Notification.vue:168
gn.get @ vue.esm.js:4482
gn.evaluate @ vue.esm.js:4587
(anonymous) @ vue.esm.js:4839
(anonymous) @ Notification.vue?b540:1
t._render @ vue.esm.js:3551
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn.run @ vue.esm.js:4557
vn @ vue.esm.js:4313
(anonymous) @ vue.esm.js:1989
Yt @ vue.esm.js:1915
Promise.then (async)
Kt @ vue.esm.js:1942
re @ vue.esm.js:1999
(anonymous) @ vue.esm.js:4405
gn.update @ vue.esm.js:4547
dt.notify @ vue.esm.js:739
set @ vue.esm.js:1064
mn.set @ vue.esm.js:4634
(anonymous) @ App.vue:178
Promise.then (async)
_fetch @ App.vue:173
_backgroundFetch @ App.vue:203
setInterval (async)
mounted @ App.vue:98
Vt @ vue.esm.js:1863
rn @ vue.esm.js:4222
insert @ vue.esm.js:3148
C @ vue.esm.js:6351
(anonymous) @ vue.esm.js:6570
t._update @ vue.esm.js:3948
r @ vue.esm.js:4069
gn.get @ vue.esm.js:4482
gn @ vue.esm.js:4471
(anonymous) @ vue.esm.js:4076
An.$mount @ vue.esm.js:9057
An.$mount @ vue.esm.js:11953
t._init @ vue.esm.js:5021
An @ vue.esm.js:5088
(anonymous) @ init.js:41
n @ bootstrap:19
(anonymous) @ bootstrap:83
(anonymous) @ notifications.js?v=db37098f:1

Network errors:

/ocs/v2.php/apps/notifications/api/v2/notifications/292

Header: Request URL: https://team.myurl.com/ocs/v2.php/apps/notifications/api/v2/notifications/292
Request Method: DELETE
Status Code: 412 Precondition failed
Remote Address: 198.46.95.195:443
Referrer Policy: no-referrer
Cache-Control: no-cache, no-store, must-revalidate
Connection: Keep-Alive
Content-Length: 31
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'
Content-Type: application/json; charset=utf-8
Date: Fri, 10 Jan 2020 09:02:53 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'
Keep-Alive: timeout=5, max=99
Pragma: no-cache
Referrer-Policy: no-referrer
Server: Apache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-IN,en-US;q=0.9,en-GB;q=0.8,en;q=0.7
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true; _ga=GA1.2.854334681.1576426250; nc_username=surabhi; km_ai=519k%2FoGt57N8oeqD4ZismrMCXgs%3D; km_lv=x; oc_sessionPassphrase=lR3B%2F3wvmchSoYwCGYnNtfq%2F45FJktT3AvzY2F2FY2OK9H7CYPeBRYirlHi%2Byxi7me%2FwHH%2Fgphwn7ElKTXPYZCl%2BCL%2BC8oQYLLDBKt71N0Rlz7mOGv0IEuRoUXxuKWxi; ocg5976uinlo=d7150dbdd3f794b90df93d6420a47e9f; nc_token=8lPeAbpmpB00CCAu8Cr8EWeqqCggfogP; nc_session_id=d7150dbdd3f794b90df93d6420a47e9f
Host: team.myurl.com
Origin: https://team.myurl.com
requesttoken: bsni0Salk8DYrzHcyP1R1kgS6fY235c3Wcd52GWgNeI=:OoaSuEjK0paczkaSrMomnyM5u8ZuvNZ7dvMMojP0BM0=
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

Preview: 

{message: "CSRF check failed"}
message: "CSRF check failed"

Response:

{"message":"CSRF check failed"}
</details>

**Comment by nickvergessen** [comment]
> `{message: "CSRF check failed"}`

Seems like your setup is a bit broken. Please seek for help at https://help.nextcloud.com/

**Comment by sirohiparag** [comment]
Okay but two problems here:

1. I have created another issue, I cannot access the https://help.nextcloud.com/ without proxy, though the apps.nextcloud.com works just fine. 

2. I did not change anything on the server and this problem just started on its own after upgrading the latest NC version. 

Can you please suggest the direction I should be looking for this problem?

**Comment by yadayadaydadaa** [comment]
Same problem. Cannot dismiss any notifications.

**Comment by nickvergessen** [comment]
> This behavior happens on a Nextcloud v 24.0.9 while I am impersonating a user

The notifications app intentionally prevents impersonated users to delete notifications.
But yeah, there is no error message in that case.

**Comment by provokateurin** [comment]
This seems to happen due to a missing `@NoCSRFRequired` annotation in https://github.com/nextcloud/notifications/blob/6c3cae661d72f63deb55b63ea0ec00721d9c8aa2/lib/Controller/EndpointController.php#L204. I don't see a particular reason why a user should only be able to delete notifications using the web ui or an app password, especially since other endpoints are accessible with a normal password. @nickvergessen could we just add the annotation to all the methods in the controller (not only deleting a notification is missing the annotation)?
