### ISSUE TITLE
Strange connection from a remote IP when activating 

### ISSUE THREAD

**Issue by zfzfzf33** [nextcloud/notifications#55]
Hi,

On a fresh Debian Jessie server, I've installed NC 10.0.2 manually without any 3rd party application. Then Upgrade -> 10.0.3. Then I've enable notifications throw the web interface.

nextcloud.log is mentionning these strange TCP 443 clients : seems to be linked to the activation of the Notifications app ...

```
146.50.149.239 - - [17/Jan/2017:14:17:40 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
146.50.149.239 - - [17/Jan/2017:14:18:01 +0100] "-" 408 - "-" "-"
146.50.149.239 - - [17/Jan/2017:14:18:10 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 404 242 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36 Edge/14.14393"
```

### Server configuration
**Operating system**:
4.8.0-0.bpo.2-amd64 #1 SMP Debian 4.8.11-1~bpo8+1 (2016-12-14) x86_64 GNU/Linux

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 15 2016 20:44:43

**Database:**
mysql  Ver 15.1 Distrib 10.0.28-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08)

**Nextcloud version:** (see Nextcloud admin page)
  - version: 9.1.3.2
  - versionstring: 10.0.3

**Where did you install Nextcloud from:**
v 10.0.2 (tar.gz / zip) from nextcloud.com then upgrade to 10.0.3

**Signing status:**

```
Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - admin_audit: 1.0.0
  - calendar: true
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - activity
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_pdfviewer
  - files_retention
  - files_videoplayer
  - gallery
  - notifications
  - password_policy
  - provisioning_api
  - user_external
  - user_saml

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxxxxxxx',
  'trusted_domains' => 
  array (
    0 => 'nextcloud.xxxxxx',
  ),
  'datadirectory' => 'xxxxx',
  'overwrite.cli.url' => 'https://nextcloud.xxxxxx',
  'dbtype' => 'mysql',
  'version' => '9.1.2.2',
  'installed' => true,
  'dbname' => 'xxxxx',
  'dbhost' => 'xxxx',
  'dbtableprefix' => 'xxx',
  'dbuser' => 'xxxxx',
  'dbpassword' => 'xxxxx',
  'defaultapp' => 'files',
  'knowledgebaseenabled' => true,
  'enable_avatars' => false,
  'allow_user_to_change_display_name' => false,
  'skeletondirectory' => '',
  'lost_password_link' => 'https://xxxxx/',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => false,
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'nextcloud.xxxxx',
  'mail_smtphost' => 'xxxxxx',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'mail_smtpdebug' => true,
  'mail_smtpsecure' => '',
  'maxZipInputSize' => 1073741824,
  'allowZipDownload' => true,
  'log_type' => 'syslog',
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'loglevel' => 2,
  'syslog_tag' => 'nextcloud',
  'logdateformat' => 'Ymd H:i:s',
  'logtimezone' => 'Europe/Paris',
  'log_query' => false,
  'log_authfailip' => true,
  'cron_log' => true,
  'log_rotate_size' => 104857600,
  'theme' => 'XXXX',
  'customclient_desktop' => 'https://nextcloud.com/install/#install-clients',
  'customclient_android' => 'https://play.google.com/store/apps/details?id=com.nextcloud.client',
  'customclient_ios' => 'https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8',
  'xframe_restriction' => true,
  'activity_expire_days' => 365,
  'trashbin_retention_obligation' => 'auto, 365',
  'versions_retention_obligation' => '31, auto',
  'appcodechecker' => true,
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'updater.release.channel' => 'stable',
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'check_for_working_htaccess' => true,
  'config_is_read_only' => false,
  'ldapUserCleanupInterval' => '51',
  'ldapIgnoreNamingRules' => false,
  'maintenance' => false,
  'singleuser' => false,
  'hashingCost' => 10,
  'max_filesize_animated_gifs_public_sharing' => 10,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess,.svn,wc.db,wc.db-journal,~snapshot,.TemporaryItems,~TEMP,Thumbs.db,desktop.ini,.DS_Store,._.DS_Store,.Trashes,XXXXXXXXXX',
  ),
  'minimum.supported.desktop.version' => '2.2.4',
  'quota_include_external_storage' => false,
  'part_file_in_storage' => true,
  'filelocking.enabled' => true,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'appstore.experimental.enabled' => true,
  'updater.secret' => 'XXXXX',
```

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration
**Browser:**
Mozilla Firefox 45.6.0

**Operating system:**
Debian 8

### Logs
see previous part

#### Browser log
no concerned

**Comment by nickvergessen** [comment]
Only one request looks odd:
```
146.50.149.239 - - [17/Jan/2017:14:18:01 +0100] "-" 408 - "-" "-"
```

The others are all good. Nothing wrong with them

**Comment by zfzfzf33** [comment]
Hi,

Thanks for your fast reply. It's a fresh server install and we are in France. I was wondering if a Nederland IP address would be included in the source code of the application to make a regular check of the state of this application... and I was wondering why.

For you it's just a coincidence ?
Have a good afternoon !

**Comment by nickvergessen** [comment]
Well one of your users should have that IP.
There is nothing in the source code which checks for the app in such a way.
