### ISSUE TITLE
Notification in notification panel

### ISSUE THREAD

**Issue by ForzaJappie** [nextcloud/notifications#552]
I am running a backup script and in the end it will create a notification for a user.

sudo -u www-data php /var/www/nextcloud/occ notification:generate admin "SomeText"

This used to generate a notification in the notification panel and in the android app. However since a couple of weeks it generates a notification in the app only. 

Has something changed?
App is installed through the app store. 

### Actual behaviour
- Tell us what happens

### Environment data
Android version:7.0
Device model: Lenovo P2
Stock or customized system:stock
Nextcloud app version:3.10
Nextcloud server version:17.02

**Comment by nickvergessen** [comment]
Please try to reauthenticate, that is the only guess I can make. Nothing else in the chain changed.

**Comment by ForzaJappie** [comment]
> 
> 
> Please try to reauthenticate, that is the only guess I can make. Nothing else in the chain changed.

Thanks, issue solved.
