### ISSUE TITLE
Notification history

### ISSUE THREAD

**Issue by claell** [nextcloud/notifications#56]
In addition to #2 showing the complete history of notifications would make sense, a bit like Dropbox does it.

(I couldn't test whether there already is a history, in that case this can be closed).

**Comment by MorrisJobke** [comment]
cc @nickvergessen @jancborchardt

**Comment by juliushaertl** [comment]
How about adding dismissed/acknowledged notifications to the activities app, just like other events from Nextcloud appear there.

**Comment by nickvergessen** [comment]
Well that is the idea and basically each app that creates notifications should do that themselves.
Not sure you need a second history in the notification drop down....

**Comment by jancborchardt** [comment]
Yes, the »History of notifications« is nothing else than the activities. When you accept a share, it shows up as something which was shared with you in the activity. When you take a call or refuse it, it shows as a call in the activity. Etc etc.

Notifications are part of activites, just a special type which requires more attention. As said from the start.

**Comment by claell** [comment]
So you don't see a need of having a history in the dropdown?

**Comment by nickvergessen** [comment]
Yes

**Comment by jancborchardt** [comment]
It might be nice to have a link to the Activity stream just in case you accepted a share or did something else by mistake. But in general I agree that there doesn’t really need to be a history if you acted on the notification. Android for example also doesn’t have anything like that.

**Comment by claell** [comment]
Alright
