### ISSUE TITLE
No pop up notifications after change Language Settings

### ISSUE THREAD

**Issue by sanek8686** [nextcloud/notifications#563]
No notifications after change Language Settings:
1. Create User 
2. Android: Install Talk, use autorization user
3. Send message to user -> Android: work (notification)
4. Change Nextcloud Settings -> Personal info -> Language -> Russia
5. Send message to user -> Android NOT work (no notification)
6. Change Nextcloud Settings -> Personal info -> Language -> English (US)
7. Android: Wipe data App and cache
8. Android: use autorization user
9. Send message to user -> Android: WORK (notification)
P.S. After 4 month ...

Ubuntu Server 18.04
nginx/1.17.4
mysql  Ver 15.1 Distrib 10.3.15-MariaDB
PHP 7.3.3-1
Nextcloud 17.0.3

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - calendar: 2.0.1
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - extract: 1.2.3
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - flowupload: 0.1.8
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.1.4
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocsms: 2.1.6
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.7.0
  - workflowengine: 1.7.0
Disabled:
  - audioplayer
  - encryption
  - federation
  - files_external
  - onlyoffice
  - recommendations
  - support
  - survey_client
  - systemtags
  - user_ldap
  - viewer

sudo -u www-data php occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***********",
            "***********"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "https:\/\/************",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/log\/nginx\/nextcloud_aut.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Moscow",
        "log_type": "owncloud",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "ocsms"
        ],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "*****",
            "*****"
        ],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by nickvergessen** [comment]
Which notification did you test with?

**Comment by sanek8686** [comment]
Nextcloud Talk v8.0.2
Send message to user, call user. No pop up notificashion

**Comment by nickvergessen** [comment]
This was actually fixed with https://github.com/nextcloud/notifications/pull/496 which is part of 17.0.3 already :thinking:

**Comment by sanek8686** [comment]
I rechecked. After change language no notification in android application.
Nextcloud 17.0.3

**Comment by alexlo0** [comment]
> 
> 
> This was actually fixed with #496 which is part of 17.0.3 already 🤔

I can confirm this issue. My NC is 17.0.3.1. After changing language to Russian the following errors appear in log:
{"reqId":"l32Ygj9YJ07RvSJyDmTi","level":4,"time":"2020-02-25T15:56:02+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"****","app":"notifications","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/chat\/abuxd47g","message":"error:0E06D06C:configuration` file routines:NCONF_get_string:no value","userAgent":"Mozilla\/5.0 (Android) Nextcloud-Talk v8.0.3","version":"17.0.3.1"}
{"reqId":"7CLOc9W5Z25EZVet8fAB","level":4,"time":"2020-02-25T16:07:58+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"****","app":"notifications","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/chat\/abuxd47g","message":"error:0909006C:PEM routines:get_name:no start line","userAgent":"Mozilla\/5.0 (Android) Nextcloud-Talk v8.0.3","version":"17.0.3.1"}
{"reqId":"hLAWUG0EDGbGNQ3waP3Q","level":4,"time":"2020-02-25T16:27:57+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"****","app":"notifications","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/room","message":"error:0909006C:PEM routines:get_name:no start line","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.3.1"}
{"reqId":"BjhlykqlBZbHEgFewoNa","level":4,"time":"2020-02-25T16:29:41+03:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"****","app":"notifications","method":"POST","url":"\/ocs\/v2.php\/apps\/spreed\/api\/v1\/room","message":"error:0406D06E:rsa routines:RSA_padding_add_PKCS1_type_2:data too large for key size","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.3.1"}

**Comment by nickvergessen** [comment]
Arg, okay I found the actual issue now. json encoding some characters does not only double them in length, but actually makes them 6 chars (`\u1234`). 
I fixed that with https://github.com/nextcloud/notifications/pull/575/files and tested it with a russian account on my phone and it does work now and exploded before.

Feel free to test and verify this on your instances
**NOTE:**  as per https://github.com/nextcloud/notifications/issues/563#issuecomment-590869154 push tokens are deleted on errors, so you need to remove the account from the talk app and create it newly.

**Comment by alexlo0** [comment]
Excellent! Now it works as expected. I've double checked with a user from scratch in Russian and another user at first in English and then changed to Russian. No errors, no broken certs. Thank you, good job!
