### ISSUE TITLE
twofactor_nextcloud_notification should use high priority notifications

### ISSUE THREAD

**Issue by mario** [nextcloud/notifications#594]
Currently only Talk has high priority notifications. This should be extended to twofactor_nextcloud_notification app as an exception.

**Comment by Valdnet** [comment]
I agree with @mario should have a high priority. Notifications for Android 9 and 10 come with a long delay or when the smartphone wakes up. The problem raised in: https://github.com/nextcloud/android/issues/5700.

**Comment by mario** [comment]
This is just for one particular app @Valdnet. Like I explained there, Android doesn't really want you to wake up the device and that's how it should stay.

**Comment by Valdnet** [comment]
> This is just for one particular app

@mario My guess is this is for the Nextcloud Android application that interests me 😉.

**Comment by mario** [comment]
No. Like I mentioned in the issue this is for the "twofactor_nextcloud_notification" server app which will generate the high priority app. And yes, it will wake up the Nextcloud Android app, but only FOR THIS, not for other things (like PhoneTrack)

**Comment by nickvergessen** [comment]
Code in question:
https://github.com/nextcloud/notifications/blob/master/lib/Push.php#L251-L257
