### ISSUE TITLE
"dismiss all notifications" button should always be visible

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/notifications#605]
### Steps to reproduce
1. have a lot of notifications
2. click on the bell icon

### Expected behaviour
when there are notifications, the "dismiss all notifications" button should always visible at the bottom of the notification window. When there are too many notifications, they should flow behind the "dismiss all notifications" button

### Actual behaviour
You see all the individual notifications but not a "dismiss all" button -  you think you have to "x" them all individually, or you scroll down by accident to discover the "dismiss all notifications" button. Bad UX.

### comments
related to https://github.com/nextcloud/notifications/issues/105

### Server configuration

**Nextcloud version:** 18.0.3

**Comment by Clementine46** [comment]
I agree with this. I also think some users might not be used to have to "close" their notifications and might end up ignoring the notifications entirely.
