### ISSUE TITLE
markProcessed including subject_parmeter?

### ISSUE THREAD

**Issue by Rello** [nextcloud/notifications#630]
Existing notifications can be marked processed
```
        $notification = $this->notificationManager->createNotification();
        $notification->setApp('analytics')
            ->setObject($object, $object_id)
            ->setSubject($subject)
            ->setUser($user_id);
        $this->notificationManager->markProcessed($notification);
```

In my case - Analytics App - thresholds are generated.
- object = constant for "Dataset"
- object_id = Report ID
- subject = constant for "threshold"

But for a report the user can maintain several thresholds, which are separated by subject_parameter
```
->setSubject($subject, $subject_parameter)
```
I would like to use the parameters to select the notification to be marked processed.
Because now, the same notification can show up many times depending on the API which might trigger it.

Is this possible?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/blob/master/lib/Handler.php#L244-L250

Right, we don't check the parameters. I guess adding that all of a sudden could break several usages in other apps.

**Comment by Rello** [comment]
Ok,
Thank you. 
I will check if i can move a unifier to the subject then
