### ISSUE TITLE
Web notifications are not persistent in operating systems notifications

### ISSUE THREAD

**Issue by dahumph** [nextcloud/notifications#634]
## Steps to reproduce
1. log in to your nextcloud 18.0.4
2. find someone to call you or mention you on talk
3. Notification shows up for only 5 seconds. After that it just dissapears, its neither persisting in Gnome's notification area nor in windows 10's. You will not have any chance to see that you missed a call. 
### Expected behavior
the **message should be persistent** in the list of received browser messages, as messages of other websites are. 
### Actual behavior
**notification popups just disappear** after a few seconds . If your turned away from the screen in that seconds, you'll miss the notification.
Further the messages are only sent to the browser while actually logged in to nextcloud. However, this might be intentionally.

**Comment by KevinLauer** [comment]
We are experiencing this as well. 
Notifications disappear after 5 seconds in the windows 10 action center. 
I already verified that my windows 10 setting for notification duration (Click Start > Settings > Ease of Access > Other options. Click on the “Show notifications for”) are working as expected with other notification. My Google Chrome settings are also working on other sites. 
When i test notifications on the website https://www.bennish.net/web-notifications.html , they are working as expected and stay as long as a configured it in the windows settings.
Another weird behavior is that notifications from nextcloud don't even stay in the action menu longer than 5 seconds, they just disappear completely.

Its the biggest issue we have with nextcloud, people are constantly missing messages and calls from nextcloud talk.

**Comment by nickvergessen** [comment]
Once we solved #703 we might be able to just kill:
https://github.com/nextcloud/notifications/blob/master/src/Components/Notification.vue#L279

**Comment by hinformatik** [comment]
Is there a soulution on it's way or is someone looking into this?
We are desperately missing this feature.

**Comment by nickvergessen** [comment]
#703 is solved by #909
