### ISSUE TITLE
Invalid navigation path

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#642]
### Steps to reproduce
1. Update Nextcloud 18.0.4 to 19.0.0 RC1.
2. Click the button "Skip to main content".
3. Click the button "Skip to navigation of app".

### Expected behaviour
There is no information about notifications on the first page after logging in.

### Actual behaviour
After logging in, I receive the following information:

![obraz](https://user-images.githubusercontent.com/47037905/81558111-6a38ca80-938d-11ea-84ea-c7c8a2fe1851.png)
**Is this intentional?**

Then after clicking: `http://xxx.xxx.pl/#app-content `and `http://xxx.xxx.pl/#app-navigation` the browser does not redirect to the given address. After deleting # in the browser address works fine.

**Nextcloud version:** (see Nextcloud admin page)
19.0.0 RC1

### Client configuration
**Browser:**
Firefox 75.0

**Operating system:**
Win10

**Comment by nickvergessen** [comment]
That page looks totally broken... Not sure what happened there for you, but this is not an issue with the notifications app at least.

**Comment by Valdnet** [comment]
I put it for notifications because the page informs about the browser's request to display notifications.

**Comment by Valdnet** [comment]
The problem was with the Rainloop app. If someone has a similar error, check how to fix it: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/151 :wink:

**Comment by lftsy** [comment]
After upgrading from 18.0.7 to 19.0.1, I did cope with the same problem. On Nextcloud default page, I had the Radio app being displayed with broken layout like this one. 
  grep radio_index /cloud/nextcloud/apps/radio/appinfo/routes.php
  $this->create('radio_index', '/')

Disabling app hides the problem

**Comment by lftsy** [comment]
This is strange because app is not validated for Nextcloud 19 but was allowed to be installed without warning on version 19. Other reports of the problem are displayed in https://apps.nextcloud.com/apps/radio
