### ISSUE TITLE
Description of the notification outside the background

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/notifications#643]
### Steps to reproduce

1. Install Talk version 9.0.0-beta. 1.
2. Go to e.g. Files or Talk.
3. Click the notification icon.

### Expected behaviour
The description of the notification should be in the background of the notification.

### Actual behaviour
The notification description is outside the notification background.

![obraz](https://user-images.githubusercontent.com/47037905/81858865-aeca8e80-9564-11ea-871a-b1fc3be7a8d4.png)

**Nextcloud version:** (see Nextcloud admin page)
19.0.0RC1

### Client configuration
**Browser:**
Firefox 76.0.1

**Operating system:**
Win10

**Comment by nickvergessen** [comment]
Yeah, just noticed that too.

**Comment by Valdnet** [comment]
For Nextcloud 19.0.0 RC2 version RC2 is now working correctly.

**Comment by MorrisJobke** [comment]
@nickvergessen I moved it to 19.0.1

**Comment by nickvergessen** [comment]
Fixed on master already i think
