### ISSUE TITLE
Loosen/remove device registration public key restrictions

### ISSUE THREAD

**Issue by jld3103** [nextcloud/notifications#648]
The restrictions about the public key in https://github.com/nextcloud/notifications/blob/a614d6ea5766e487bda1d39a820b61307fef0334/lib/Controller/PushController.php#L93 are not good, because many libraries produce public keys that have other lengths than the expected 450. so the restrictions on the public key format are not helping developers to integrate push notifications in their app, but make it harder,
I'm currently adding a bunch of `\n`'s to fix the problem,but that is really not a good solution.

I would propose to either loosen or completely remove (that shouldn't be the way to go) the restrictions.

**Comment by nickvergessen** [comment]
Well, we require `rsa2048` keys and their format+length is pretty fixed I think.
