### ISSUE TITLE
Subscribing at the Push Proxy

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/notifications#65]
Please verify : 

https://push-notifications.nextcloud.com

Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSLocalizedDescription=An SSL error has occurred and a secure connection to the server cannot be made., NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, NSUnderlyingError=0x16b0bdc0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, _kCFNetworkCFStreamSSLErrorOriginalValue=-9802, _kCFStreamErrorCodeKey=-9802, _kCFStreamErrorDomainKey=3, kCFStreamPropertySSLPeerTrust=<SecTrustRef: 0x15627cc0>, kCFStreamPropertySSLPeerCertificates=(
    "<cert(0x159bce00) s: demo.nextcloud.com <http://demo.nextcloud.com/> i: Let's Encrypt Authority X3>",
    "<cert(0x159c0200) s: Let's Encrypt Authority X3 i: DST Root CA X3>"

"<cert(0x159bce00) s: demo.nextcloud.com <http://demo.nextcloud.com/> i: Let's Encrypt Authority X3>",
    "<cert(0x159c0200) s: Let's Encrypt Authority X3 i: DST Root CA X3>"
), NSErrorClientCertificateStateKey=0, NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x15627cc0>,

**Comment by nickvergessen** [comment]
Please stop creating the same issue every where. The task has been forwarded and will be resolved.

**Comment by MorrisJobke** [comment]
Should be fixed by now

**Comment by marinofaggiana** [comment]
... over 8 days ....
