### ISSUE TITLE
Multiple systray notifications

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/notifications#703]
- have multiple browser windows open
- receive talk/federated share/etc notification
- see that it is not only 1x, but 2-4x the same message.

**Comment by nickvergessen** [comment]
Random thought:

Save in browser storage the list of notifications that have been pushed (shared between browser tabs). If the id is already in the list, don't push even when the tab sees it for the first time

**Comment by nickvergessen** [comment]
While doing this we could also just share the full notification list across all tables, saving them from pulling every 30 seconds.

**Comment by nickvergessen** [comment]
Still happening sometimes

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/notifications/pull/909
