### ISSUE TITLE
Add an API endpoint so users can send themselves a notification without an admin password

### ISSUE THREAD

**Issue by bnjbvr** [nextcloud/notifications#706]
It would be nice that I, as a user, don't require an admin password to be able to send myself notifications. The use case for this is to use Nextcloud as a notification hub, through other applications that would call this API endpoint, using a user app-token instead of an admin app-token. Of course, this means an additional check is required to make sure the notification's receiver is actually the user (alternatively: the to field is ignored, and the user on which behalf the request was sent is notified by default).

Thanks for all your work there, I am a huge fan of Nextcloud :-)

**Comment by nickvergessen** [comment]
Duplicate of #83
