### ISSUE TITLE
no notifications after 11.0.3 nextcloud upate

### ISSUE THREAD

**Issue by summerjob** [nextcloud/notifications#80]
after updating nextcloud to v11.0.3 I receive no more notifications
bell also never shows

nginx & nextcloud error log is clean.
is it just me?

ubuntu 16.04 // nginx // php7 // mariadb

**Comment by nickvergessen** [comment]
The bell only shows when you have a notification. That was always like this and still works for me on my home instance.
What kind of notification are you missing?

**Comment by summerjob** [comment]
Actually no notifications are showing at all. I upload new files, share files, mention name in comments, invite to video call, nothing shows up.

I do have the some php errors caused by news & mail regarding htmlpurifier (I already checked - these are know issues)  but even if I turn both mail & news plugins off notifications still don't show up.

The only thing I recently changed on my system was changing permissions
`sudo chown -R www-data:www-data /var/www/html/nextcloud`
so the auto-update could make file changes.
Now that I read the words _auto-update_ again I have a bad feeling in my stomach. I know I had some notifications right before I did the update.

**Comment by nickvergessen** [comment]
Can you check, whether there are any entries in the oc_notifications table?

**Comment by MorrisJobke** [comment]
> Actually no notifications are showing at all. I upload new files, share files, mention name in comments, invite to video call, nothing shows up.

* uploading files doesn't cause a notification
* sharing a file also not (only a received federated share cause a notification)
* mentioning only cause a notification for the mentioned person if the file is also available for this person
* inviting somebody to a video call should cause a notification for the invited person

**Comment by summerjob** [comment]
Thank you Morris for clarifying what shows up under notifications. I was under the impression that all relevant events show up there, in particular _new files_ & _new emails_. To me personally new files & emails are the most important events in a cloud, so it would be nice to know if there's any way to enable notifications for this?

**Back to my issue**
I have now successfully received notification under the following conditions:
- comment on file that is available to mentioned person causes immediate notification
- announcement through announcement center causes notification after next cron job 

Video call invite still doesn't initiate any notification (alos no entry in oc_notifications table for this)
Are there any other events I could test that should receive notifications?

There is one error log entry that gets added each time I call the admin menu (and only then):
`access forbidden by rule, client: 49.123.123.123, server: example.com, request: "GET /data/.ocdata?t=1494350109734 HTTP/2.0", host: "example.com"`
No idea if that's relevant.
btw, thank you both for your fast response on issue reports, feels like premium support already :)

**Comment by nickvergessen** [comment]
Please provide the information that is requested in the issue template:
https://github.com/nextcloud/notifications/issues/new

Most important: list of apps, signing status, browser and server log.
