### ISSUE TITLE
Please Provide a Hello World Example

### ISSUE THREAD

**Issue by HouraisanNEET** [nextcloud/notifications#916]
**Is your feature request related to a problem? Please describe.**
The document https://github.com/nextcloud/notifications/blob/master/docs/notification-workflow.md is way too complicated to understand.

**Describe the solution you'd like**
A Hello World notification example.

**Comment by nickvergessen** [comment]
Well there are a lot of apps in https://github.com/nextcloud which implement the OCP\Notifications\INotifier interface. That's the best you can copy but it's also what is at the end of the doc link.
And for generating the notifications you can search for the `createNotification` method I'm the organization for several examples, but this is nothing you can copy and you need to fill it with your data
