### ISSUE TITLE
Remove annoying notification of incomplete profile information

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/notifications#92]
This announcement occurs daily and is annoying, because I know this and I don't want to add more information to my profile. At least it would be nice, if I could say "Don't show this notification anymore". As far as I see, this notification affects the windows and the iOS clients, too.

I am not sure if this has to be handled here or in the anouncement app. In this case move this issue or give me a hint, I will open it there. 

![grafik](https://user-images.githubusercontent.com/26707476/30576697-e2a6f4a6-9d09-11e7-98dd-dede691f0d36.png)

**Comment by nickvergessen** [comment]
Just hover the notification, then you should see a ✖ in the top right corner of it. When you click on that its being deleted and will never bug you again.

**Comment by dartcafe** [comment]
Cool. Didn't know that, as well as the users, who reported this to me. Maybe there is a plan of creating a more intuitive solution?
